### ISSUE TITLE
Instances broken after upgrading to Windows 10 1903

### ISSUE THREAD

**Issue by freemaths** [CanonicalLtd/multipass#1012]
Windows 10 recently upgraded itself to 1903 build 18362.295 My multipass instance was working fine before this upgrade.

Now "multipass list" shows "No instances found" and if I use Hyper-V manager the instance is shown as "saved" but will not start. If I try to start it in Hyper-V I get the following error:

[Window Title]
Hyper-V Manager

[Main Instruction]
An error occurred while attempting to start the selected virtual machine(s).

[Content]
'vm' failed to restore.

Microsoft Emulated IDE Controller (Instance ID 83F8638B-8DCA-4152-9EDA-2CA8B33039B4): Failed to restore with Error 'A virtual disk support provider for the specified file was not found.'.

Failed to open attachment 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx'. Error: 'A virtual disk support provider for the specified file was not found.'.

Failed to configure 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx': The storage where the virtual hard disk is located does not support virtual hard disk sharing.

The Hard Disk Image file 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx' does not exist.

[Expanded Information]
'vm' failed to restore. (Virtual machine ID D445193A-7DC1-44E7-8ED1-A8626CBFAB6C)

'vm' Microsoft Emulated IDE Controller (Instance ID 83F8638B-8DCA-4152-9EDA-2CA8B33039B4): Failed to restore with Error 'A virtual disk support provider for the specified file was not found.' (0xC03A0014). (Virtual machine ID D445193A-7DC1-44E7-8ED1-A8626CBFAB6C)

'vm': Failed to open attachment 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx'. Error: 'A virtual disk support provider for the specified file was not found.' (0xC03A0014). (Virtual machine ID D445193A-7DC1-44E7-8ED1-A8626CBFAB6C)

'vm': Failed to configure 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx': The storage where the virtual hard disk is located does not support virtual hard disk sharing.

The absolute path 'C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\vm\ubuntu-18.04-server-cloudimg-amd64_74CD6322-AB10-4735-8828-4A255DA0327F.avhdx' is valid for the '' Hard Disk Image pool, but references a file that does not exist.

[^] Hide details  [Close]

**Comment by Saviq** [comment]
Hi @freemaths, sorry you stumbled on that… Can you launch new instances?

It sounds bad that you can't launch the instance in the Hyper-V Manager… We'll have to dig what caused this, but looks like something Hyper-V does wrong in the upgrade.

Not sure yet where the `.avhdx` files come from, ours should be `.vhdx`. What you could try to do is see what the VM hard drive is configured as, and change it to point at the correct `.vhdx` file.

Let us know if you get anywhere and we'll dig on our side.

**Comment by freemaths** [comment]
Yes, I managed to create and start a new instance (but had to reboot windows in the process), so am up and running. I've not deleted the old instance so can help with finding the problem if needed.

Note: the new working instance disk is also named .avhdx

It looks like Windows upgrade has just lost, corrupted or deleted the old file. There is no sign of it or the directory it should be in.

**Comment by townsend2010** [comment]
I looks like _something_ removed the disk image checkpoint file, ie, the `avhdx` file.  This is from when (presumably) the instance was running and was "suspended" when the Multipass daemon was shutdown during upgrade.  It's not clear why the checkpoint was removed.

Doing a search on missing .avhdx's, it looks like this can happen for reasons that is still unclear to me, but it seems there may be manual steps you can do to recover the VM.  Once recovered, I think it would be possible to restart the Multipass service and it would then pick up the instance since there is no error with it.

**Comment by freemaths** [comment]
Happy to test any recovery options if you let me know what to try.

Everything is up and running with a new instance so I'll just hang on to the old one for anything you might like testing.

**Comment by Saviq** [comment]
We will have to try and document how to recover those instances manually.

**Comment by freemaths** [comment]
I have now deleted the instance. I had a good search of the disk and could not find it so I think it had just become a ghost configuration. Microsoft updates look to often cause problems for VMs. I suspect in future I need to make sure all VMs are shut down before any updates are applied. I will close this issue.

**Comment by ricab** [comment]
I suspect that this and #1119 are manifestations of the same problem. In case this is of any use to anyone, perhaps instances could be recovered from `C:\Windows.old` too.
