### ISSUE TITLE
Lost access to multipass instance on windows

### ISSUE THREAD

**Issue by adrianharabula** [CanonicalLtd/multipass#1016]
Running on windows:
```
C:\Users\Adrian>multipass version
multipass  0.8.0+win
multipassd 0.8.0+win
```

I lost access to instance
```
C:\Users\Adrian>multipass info bar
info failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'
```

Is there a way to regain access to it? Restarting instance is not solving the issue. Neither restarting host machine.

Creating a new instance works, but looks like 'bar' one is lost, even if it says running:
```
C:\Users\Adrian>multipass list
Name                    State             IPv4             Image
bar                     Running           N/A              Ubuntu 18.04 LTS
```

**Comment by Saviq** [comment]
Hi @adrianharabula looks like you're running under VirtualBox, right?

You should be able to access the VBox GUI using:
```
psexec -s -i VirtualBox.exe
```

You can find the psexec tool [here](https://docs.microsoft.com/en-us/sysinternals/downloads/pstools), and `VirtualBox.exe` is usually in `C:\Program Files\Oracle\VirtualBox`. See if you can find / start the instance there and if you can recover it that way.

Let us know!

**Comment by adrianharabula** [comment]
Hello @Saviq 

Thanks for very fast response!

Here is what I get when I run psexec
```
C:\Program Files\Oracle\VirtualBox>psexec -s -i VirtualBox.exe

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


PsExec could not start VirtualBox.exe on DESKTOP-FI0SA3U:
The system cannot find the file specified.
```

**Comment by adrianharabula** [comment]
Got it with:
```
psexec64 -s -i "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe"
```

I'm looking now if I can restore the instance.

**Comment by adrianharabula** [comment]
Incredible! I got the instance back!!!

It looked like there was a kernel panic occuring that was not making the instance accesible. After a few random restarts while trying to gain access to the instance, it suddely started to work.

Thanks a lot @Saviq!

**Comment by Saviq** [comment]
Nice! @adrianharabula note you may need to reboot (or just `PS> Restart-Service Multipass`) for Multipass to be able to launch new instances, as the VirtualBox GUI puts a lock of some kind on the instances and they may fail to launch if the GUI was started.
