### ISSUE TITLE
Document `get/set` options in `multipass help`

### ISSUE THREAD

**Issue by robertolabarca** [CanonicalLtd/multipass#1023]
**example**

> `c:\>multipass config`
> Error: Unknown Command 'config' (try "multipass help")

>`c:\> multipass set local.network="192.168.0.1/24" `
>Unrecognized settings key: 'local.network'

**Comment by ricab** [comment]
Hi @robertolabarca, you can get the available commands with `multipass help`, but indeed we still did not document available configuration keys. We intend to do it soon, but for now we support only `client.primary-name` (string respecting instance naming constraints) and `local.driver` (e.g. 'hyperv', 'virtualbox').

**Comment by robertolabarca** [comment]
@ricab .  Thank you for your reply. but how to change network parameters

**Comment by Saviq** [comment]
@robertolabarca it is currently not possible, and I actually think you're after #118 rather than configuring Multipass on the same subnet (that is likely to break).

Unless there's another reason why you'd like to change the subnet?
