### ISSUE TITLE
Instance is in Unknown state, Hyper-V Mgr shows multiple instances with same name

### ISSUE THREAD

**Issue by markl11** [CanonicalLtd/multipass#1059]
I am using multipass with Windows 10 and I have a multipass instance in an 'unknown' state - can't connect to it from multipass.
When I look in Hyper-V manager I have four instances with the name of the multipass instance - all created on different dates. 
I can actually start the instance from multipass (ie. I issue 'multipass start <instance> and I can see it start in Hyper-V manager) and I can even start any of those instance in Hyper-V and if I look at the console in Hyper-V I can see them start correctly, but still can't connect to the instance from multipass ('multipass shell <instance name>').
Really need to be able to access the instance but I am stuck.

![ScreenHunter 1083](https://user-images.githubusercontent.com/38077229/64858070-45cdf800-d61e-11e9-8ed0-791acb99a3f2.png)
![ScreenHunter 1082](https://user-images.githubusercontent.com/38077229/64858076-48c8e880-d61e-11e9-93ec-f7e62b95e148.png)

**Comment by Saviq** [comment]
Hi @markl11 this looks really twisted, any idea how it ended up like this? Have you been using the `amicable-lamb` name yourself? Did you reinstall Multipass recently? Maybe upgrade Windows?

If you open the running instance in Hyper-V, can you see it booting fine?

Do you have important data inside the instance, or could you start from scratch?

**Comment by markl11** [comment]
Hi, @Saviq when I had this problem I did re-install the same version of multipass (0.8.0). But the state as shown in my screenshots/as described was the same before the re-install and after the re-install. Didn't seem to change the situation.

Unfortunately, I do have important data in the instance, so any help on recovering the instance much appreciated.

**Comment by markl11** [comment]
Would it be possible to rename the older instances for example to try to recover the instance. I ask because I have noticed that when i issue a 'multipass start' more than one of the instances with that name attempts to start in Hyper-V. Perhaps multipass is getting confused with the multiple VMs with the same name?

**Comment by Saviq** [comment]
@markl11 I don't think we can be certain _which_ `amicable-lamb` is it that has your data… we can assume it's the first one, but there's always a chance it is not. Then again all of them are likely to point to the same disk image…

Can you start a new instance? Say `multipass launch --name recovery`? If so, stop the broken ones and have a look at their disk setup - you can attach that disk to the new instance and then we can help you hook it up.

If even new instances are broken, you'll have to manually create a VM, easiest will probably be the Ubuntu Desktop one.

**Comment by Saviq** [comment]
@markl11 are you on IRC? We're in `#multipass` on Freenode, you could also join via web:

https://webchat.freenode.net/#multipass

**Comment by Saviq** [comment]
@markl11 yes it's likely that the name confuses Multipass, or the Default Switch, responsible for giving up IPs for the instances.

Another thing to try: can you `ping amicable-lamb.mshome.net`? Or maybe notice the IP flying by when booting the instance?

If so, you should be able to ssh into it, we can tell you where the SSH keys are stored on your host.

**Comment by markl11** [comment]
@Saviq I tried renaming the instances and I am now able to start and stop the affected instance using 'multipass start' & 'multipass stop'. Only problem now is that the instance does not get an IP address. I have tried the ping above and I get a 92.x.x.x address but I can't connect. I noticed that other multipass instances (apart from amicable lamb) get a 172.x.x.x as shown in 'multipass list'.
Any ideas?

**Comment by Saviq** [comment]
@markl11 I think the Default Switch got very confused with this, are you able to see a 172.* IP address flying by when starting the `amicable-lamb` instance from Hyper-V manager? Like, when you open its console?

**Comment by markl11** [comment]
@Saviq I have actually now managed to get into it. I found that 3 of the 4 duplicate instances of 'amicable-lamb' would boot but not obtain an IP, but 1 did obtain an IP address - and I am now able to get into it ('multipass shell'). Just checking now whether everything is there - so far seems to be.....

**Comment by Saviq** [comment]
@markl11 that's awesome, again - I have no idea how this came to be… but I think at least one thing we've learned is that we need to refer to instances by UUID rather than name, since those are not unique on Hyper-V…

**Comment by markl11** [comment]
Seems ok but with one big caveat - it has lost Internet access....investigating.

**Comment by Saviq** [comment]
@markl11 this all really shows something gone wrong with the Default Switch (it's provided by Windows), do new instances get internet access fine? Can you ping between instances using their 172.* addresses?

**Comment by markl11** [comment]
@Saviq ok - fixed this issue too - the '/run/systemd/resolve/' directory had somehow disappeared. So, created that directory, created a new 'resolv.conf' with contents copied from another multipass instance and hey presto now working.
I thiiiiiink it is back to normal now...fingers crossed.

**Comment by Saviq** [comment]
@markl11 great investigation :)

The lack of `/run/systemd/resolve` again suggests something went wrong with DHCP (it should be created automatically - note it will go away after a reboot).

Glad you got it going and really sorry you had to fight through this… If you think there's things that we can improve that would help you recover, let us know!

**Comment by markl11** [comment]
@Saviq thanks. All part of the fun :-)

**Comment by Saviq** [comment]
Will close this now and we'll deal with the fallout separately.

**Comment by markl11** [comment]
This issue is still affecting me. It seems that everytime Microsoft do an OS update this issue re-occurs. As such multipass is proving to be unusable on Windows 10 at the moment.

**Comment by yingshaoxo** [comment]
> This issue is still affecting me. It seems that every time Microsoft does an OS update this issue re-occurs. As such multipass is proving to be unusable on Windows 10 at the moment.

Windows is a shitty system for this unstable reason. (After you restart, you found that everything you have set up well at ubuntu system, it's gone! What a time-wasting by using Windows!)

**Comment by suhrab** [comment]
@Saviq 
I also faced same issue as @markl11
I am on Windows 10 OS build 19043.1110. If you look on screenshot, the duplicates with the same name appeared on 24 Aug, almost the same time.
I renamed these copies and it works now.
![image](https://user-images.githubusercontent.com/4409852/131286354-245b3274-0f29-4430-ba12-27aaf487578e.png)

**Comment by suhrab** [comment]
Sending you Windows update history screenshot. I dont see any update installed on Aug 24
![image](https://user-images.githubusercontent.com/4409852/131286914-da4cb08d-44e2-41b8-b5d3-3ea0165f3cc6.png)
