### ISSUE TITLE
Multipass cannot connect to /run/multipass_socket in GitHub Actions ubuntu-latest VM

### ISSUE THREAD

**Issue by sirredbeard** [CanonicalLtd/multipass#1075]
I am attempting to automate the building and publishing of a snap to the Snap store in the ubuntu-latest VM in GitHub Actions.

Snapcraft relies on multipass for building snaps. Invoking multipass fails on the ubuntu-latest VM on GitHub Actions with the following errors:

```
$ sudo multipass list
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/run/multipass_socket' is accessible
```
```
$ snapcraft
Launching a VM.
launch failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/run/multipass_socket' is accessible
```

I have attempted the following remediation:

- Adding `sudo chown root:root /` to my workflow
- Ensuring my VM user is in sudo group with `sudo usermod -aG sudo $USER`
- Manually starting multipassd with `sudo snap start multipass` before invoked
- Ensuring permissions are set properly the socket `sudo chown $USER:$USER /run/multipass_socket` but this fails without a `sudo touch /run/multipass_socket` because it can never find `/run/multipass_socket`

To duplicate:

- Create a new GitHub repository on an account with GitHub Actions enabled.
- Create a new workflow.
- Copy and paste GitHub Actions workflow from [here](https://gist.github.com/sirredbeard/4c538d71d7657d8e6caf84bb5025ef72).
- Run workflow.

Use case:

Ubuntu is the primary Linux distro on GitHub actions and comes with snapd pre-installed. Snaps are an excellent way to handle dependencies when building with GitHub Actions. It would be useful to be able to build snaps on the same platform. GitHub Actions support would be particularly useful for pushing new releases from GitHub to the Snap store.

![Annotation 2019-09-19 101140](https://user-images.githubusercontent.com/33820650/65251791-f415e980-dac5-11e9-8a3c-8f62bb70b652.png)

**Comment by sirredbeard** [comment]
The solution to this problem is to use the Snapcraft Docker container instead of the raw Ubuntu VM on GitHub actions. Snapcraft, multipass, and everything work fine in that managed container.

**Comment by townsend2010** [comment]
@sirredbeard,

Thanks for letting us know that you found a solution.  We'll keep it in mind if someone else runs up against this issue in the future.

**Comment by LyzardKing** [comment]
sorry for posting in a closed issue, but what if the docker container is not good enough?
I need to build a core18 snap, but the docker image will not work properly:
`The following snaps are required but not installed as snapcraft is running inside docker or podman container: core18.`

**Comment by Saviq** [comment]
@LyzardKing that doesn't seem like a Multipass issue?

**Comment by TravisEz13** [comment]
It would be nice if this someone would work with the Azure Dev Ops team to get this working.
