### ISSUE TITLE
Multipass for windows 0.8.0 not working

### ISSUE THREAD

**Issue by marcello-mirenda** [CanonicalLtd/multipass#1077]
I installed multipass on Windows 10 1903 with hyper-v enabled and is not working.
I got this
```
Name                    State             IPv4             Image
mmi-01                  Unknown           --               Ubuntu 18.04 LTS
```
the network seems ok
```
Pinging mmi-01.mshome.net [172.17.217.206] with 32 bytes of data:
Reply from 172.17.217.206: bytes=32 time<1ms TTL=64
Reply from 172.17.217.206: bytes=32 time<1ms TTL=64
Reply from 172.17.217.206: bytes=32 time<1ms TTL=64
Reply from 172.17.217.206: bytes=32 time<1ms TTL=64

Ping statistics for 172.17.217.206:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```
I got also 
```
=> multipass exec mmi-01 -- lsb_release -a
exec failed: Cannot retreive credentials in unknown state
```
Thanks in advance
Marcello

**Comment by Saviq** [comment]
Hi @marcello-mirenda what happened when you were trying to `multipass launch` it?

**Comment by marcello-mirenda** [comment]
Hi @Saviq nothing. Everything went well also with "-v -v -v". No messages.
I have uninstalled Hyper-V, cleaned all the drivers for network interfaces using the device manager. I have uninstalled multipass. With all network interfaces cleaned I have installed again everything but same result, not working.

FYI I tried in an another machine and it worked. At this point It's hard for me to figure out what was wrong in my development machine.

**Comment by marcello-mirenda** [comment]
Hi @Saviq I solved the problem.
I launched a shell under the LocalSystem account
` .\PsExec.exe -i -s cmd`
then I launched the daemon
`C:\Program Files\Multipass\bin>multipassd.exe --logger stderr -V debug`
This was the log:
`[2019-09-24T11:35:03.340] [debug] [mmi-01] Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new`

As you can see I had a problem with the powershell module PSReadLine version 1.2.

I have replaced PSReadLine 1.2 with PSReadLine  2.0.0-beta4 and everything went well.

I don't know why this problem exists. Anyway I solved the problem as described.
Thank you
