### ISSUE TITLE
microk8s.enable dns dashboard storage failed inside multipass

### ISSUE THREAD

**Issue by ycheng** [CanonicalLtd/multipass#1083]
Saw some document that microk8s works inside multipass, so I try.

```
$ multipass launch bionic -n kubeflow115 -m 8G -d 40G -c 2
$ multipass shell kubeflow115
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install snapd
$ sudo -s
# snap install microk8s --classic
# microk8s.status --wait-ready
# microk8s.enable dns dashboard storage
```
Then I got the attached error. Seems related to access to 127.0.0.1

[microk8s-in-multipass.log](https://github.com/CanonicalLtd/multipass/files/3647124/microk8s-in-multipass.log)

**Comment by townsend2010** [comment]
Hi @ycheng,

I'm able to reproduce the issue you see following your steps.  I'd like to follow up with the microk8s folks, so I'd like to know where you found these steps so I can reference them when I talk to them them.

Thanks!

**Comment by ycheng** [comment]
@townsend2010 it's in web page: https://ubuntu.com/kubeflow/install to enable "dns storage dashboard". Thank you!

**Comment by townsend2010** [comment]
@ycheng, ok, thanks.  I'll see if I can follow up with that team.

**Comment by townsend2010** [comment]
@ycheng,

I filed an issue with the microk8s project at ubuntu/microk8s#674.  Hopefully they can help out some on what may be happening here.

**Comment by ktsakalozos** [comment]
This issue is on MicroK8s. A PR with a fix is on the way and a workaround is described in  https://github.com/ubuntu/microk8s/issues/674 . Feel free to close this issue here.

**Comment by townsend2010** [comment]
@ktsakalozos,
Thanks for your help on this!!

@ycheng,
I'm going to close this issue and you can refer to ubuntu/microk8s#674 for the workaround if you'd like.
