### ISSUE TITLE
MacOS - Forbidden: body content-type denied when launching

### ISSUE THREAD

**Issue by whizard** [CanonicalLtd/multipass#1090]
When I try to issue the command on a fresh install of multipass I get the following error:

multipass launch --name k3s-master --cpus 1 --mem 512M --disk 3G -v

launch failed: failed to download from 'http://cloud-images.ubuntu.com/releases/server/releases/bionic/release-20190918/unpacked/ubuntu-18.04-server-cloudimg-amd64-vmlinuz-generic': Error transferring http://cloud-images.ubuntu.com/releases/bionic/release-20190918/unpacked/ubuntu-18.04-server-cloudimg-amd64-vmlinuz-generic - server replied: Forbidden: body content-type denied

I think the issue is that the images are still being reference via http instead of https.

**Comment by townsend2010** [comment]
Hmm, this sounds like some issue on the server.  Does it still occur for you?

**Comment by whizard** [comment]
Yes it is still happening. It goes through the Retrieving Image and then it gives the Forbidden message after it hits 100%

**Comment by townsend2010** [comment]
Hmm, ok.  A search of what "Forbidden: body content-type denied" often indicates that a proxy is being used and is misconfigured some how.  Are you using a proxy?  Or perhaps some other network protection mechanism?

**Comment by townsend2010** [comment]
Also, does clicking on the link you posted above work for you in a web browser?

**Comment by whizard** [comment]
Well, we do have a firewall (WatchGuard) which detected it as being an EXE/DLL and blocked it. Sorry to bother you. I should have checked the firewall log first before bothering you.

Thanks!

**Comment by whizard** [comment]
This was a firewall issue

**Comment by townsend2010** [comment]
@whizard,

No worries, glad to help :smile:
