### ISSUE TITLE
macOS: “multipass-gui” > “Multipass”

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/multipass#1091]
A screenshot in #1082 reveals that the Multipass app is labelled “multipass-gui”.

Following #1078, it should be “Multipass” instead.

**Comment by ricab** [comment]
Thank you for highlighting that. Notice #1078 concerned windows only. But yes, the same principle stands on mac, so this will indeed have to be a concern when implementing #968. TBH, I am not really sure what's putting that icon in there ATM.

**Comment by Saviq** [comment]
Yeah this dock icon will not be there when we've done all that's needed to autostart the icon on login.

I'll mark this as dupe of #968 then.

**Comment by Saviq** [comment]
Duplicate of #968
