### ISSUE TITLE
Move to different machine

### ISSUE THREAD

**Issue by wiradikusuma** [CanonicalLtd/multipass#1134]
Let say I have already set up a VM(?) in a Windows machine, how do I move/copy it to a different Windows machine?

Also, if I want to run it in other OS, will it work the same?

**Comment by Saviq** [comment]
There is no built-in support for that at the moment, there's an issue for it, though: #208.

You can try manipulating Multipass's data, there's some info about the file locations on Windows in #1119.

**Comment by Saviq** [comment]
Duplicate of #208
