### ISSUE TITLE
[feature request] Support for NAT network on Hyper-V virtual switch

### ISSUE THREAD

**Issue by hnakamur** [CanonicalLtd/multipass#1153]
First of all, thanks for creating and sharing a nice software!

I tried multipass 0.8.0 on Windows Hyper-V, and found the IP address of the vEthernet (default switch) changes every time after Windows reboot.

In my use case I add an entry of VM to the hosts file of Windows and Windows Subsystem for Linux.
This is needed to access servers in VM using hostnames from browsers on Windows or ssh and curl on Windows Subsystem for Linux.

In this setup, I have to edit the hosts every time after Windows reboot.

Then I found that I can use static IP address if I [Set up a NAT network | Microsoft Docs](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network).
However after I did this setup, multipass no longer recognize the VM. Actually the multipass service does not start anymore after Windows reboot.
I can use the VM itself via Hyper-V manager without multipass.
But multipass support for NAT network on Hyper-V virtual switch would be great.

Thanks!

**Comment by Saviq** [comment]
Hi @hnakamur,

You can simply use `<instance>.mshome.net` as the hostname for the instance :)

The VMs are connected to the Default Switch Hyper-V network that gives out the IP addresses, but it also serves the DNS for them under the `.mshome.net` domain :)

Hope this helps, please reopen if that doesn't work for you or isn't enough.

**Comment by mikhail-khalizev** [comment]
Consider the situation. There is Windows with Hyper-V. And I need to forward ports (NAT) from the internet to a Linux VM. 
Is it possible to configure through multipass?

**Comment by Saviq** [comment]
@mikhail-khalizev you can [use `--network`](https://multipass.run/docs/additional-networks), your instance would then get an IP on your physical network. You can then forward the relevant ports on your router.
