### ISSUE TITLE
Multipass not working with Z Shell on Mac Catalina

### ISSUE THREAD

**Issue by PrernaWeb** [CanonicalLtd/multipass#1156]
Cannot get Multipass to launch using Z Shell (new default shell) on catalina. Command apparently does nothing? Changing the shell default back to Bash works.

**Comment by Saviq** [comment]
Hi @PrernaWeb,

It's probable that you don't get the `multipass` command on your `PATH` (the variable that tells the shell where to look for binaries).

Can you do a couple tests for me please, in both Z Shell and Bash?
```console
printenv PATH
which multipass
```

**Comment by PrernaWeb** [comment]
> Hi @PrernaWeb,
> 
> It's probable that you don't get the `multipass` command on your `PATH` (the variable that tells the shell where to look for binaries).
> 
> Can you do a couple tests for me please, in both Z Shell and Bash?
> 
> ```
> printenv PATH
> which multipass
> ```

OK, path is 
![image](https://user-images.githubusercontent.com/19397253/68208470-16f25380-ffc9-11e9-9718-9226e34fb696.png)
which mulltipass is /usr/local/bin/multipass

**Comment by Saviq** [comment]
Huh, @PrernaWeb so my initial diagnosis was wrong. Multipass seems to be set up correctly.

Can you please paste exactly what are you doing and what's happening (maybe use `-vvv` to get more logging output)?

**Comment by PrernaWeb** [comment]
@Saviq just did a macos update and the problem has disappeared.. Thanks for looking into it, will let you know if I can reproduce down the line.
