### ISSUE TITLE
macos: unable to find any images or launch any instances

### ISSUE THREAD

**Issue by BenWibking** [CanonicalLtd/multipass#1169]
I've installed the 0.8 release via the .pkg installer on macOS 10.15.1, but `multipass find` returns

```
~ multipass find
No images found.
```

and `multipass launch` fails with the error:

```
~ multipass launch ubuntu
launch failed: Remote "" is unknown or unreachable. 
```

**Comment by Saviq** [comment]
Hi @BenWibking this suggests Multipass is having trouble accessing the Internet.

Have a look at our [macOS network troubleshooting](https://discourse.ubuntu.com/t/troubleshooting-networking-on-macos/12901) page, hopefully it points somewhere interesting.

In short: any VPN / Firewall software running? You'll have to exempt Multipass from being blocked.

**Comment by arashkaffamanesh** [comment]
@BenWibking you are on Catalina, Multipass doesn't work as it should.
@Saviq there was a pkg v0.9. RC, which is apparently deleted.
Is there any plan to release 0.9 stable?

**Comment by Saviq** [comment]
@arashkaffamanesh @BenWibking the almost-final (unsigned, we're getting this done now) packages are available here:

https://github.com/CanonicalLtd/multipass/commit/474f2d551eb1a1288f0b8a81f0174c48a7b41528#commitcomment-35789190

That said, the above issue doesn't look like anything we know we've loved in the new release.

**Comment by BenWibking** [comment]
Nothing except the build-in firewall is running as far as I'm aware. I've disabled 'block all incoming connections' as described on the troubleshooting page. The bootpd daemon is not running, but when I start it manually, nothing changes with multipass behavior.

**Comment by Saviq** [comment]
@BenWibking can you see any issues in `/Library/Logs/Multipass/multipassd.log`? You could also pass `-vvv` to any of the commands to potentially see some detail about the failure.

**Comment by BenWibking** [comment]
```
➜  ~ multipass find -vvv                       
[2019-11-11T11:47:40.222] [warning] [VMImageHost] Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Unknown error

[2019-11-11T11:47:40.538] [warning] [VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Unknown error

[2019-11-11T11:47:40.541] [warning] [VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/releases/streams/v1/index.json': Unknown error

[2019-11-11T11:47:40.542] [warning] [VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/daily/streams/v1/index.json': Unknown error

No images found.
```

The same warnings show up in the logfile.

**Comment by Saviq** [comment]
@BenWibking can you download those files directly? Like with `curl` or `wget`?

If not, there's something in your network preventing access to those files… If yes, there's something in your system / network preventing `multipassd` retrieving them. The only examples we know of that do something of the sort are Little Snitch, any firewall solution or maybe VPN software.

**Comment by BenWibking** [comment]
Yes, I can download the files directory with wget.

I did have Little Snitch running with the network filter active (but with silent mode -- allow all connections mode). When I disable the network filter, it works and I can download and launch images. This is extremely strange behavior, because on my secondary MacBook where Little Snitch is also installed and active, I can download and launch images with the network filter active. Both MacBooks are running Catalina with the latest version of Little Snitch.

**Comment by Saviq** [comment]
@BenWibking glad you finally got this going. It's not really weird that instances behave differently from the `multipassd` daemon, their network traffic shows up as packets on the `br100` bridge, not as packets coming from `multipassd`. In any case, this shows that Little Snitch is the problem, and you can probably whitelist `multipassd` there.

I have expanded the section on Little Snitch in [the troubleshooting doc](https://discourse.ubuntu.com/t/troubleshooting-networking-on-macos/12901) and will close this issue.

Please reopen if you find out if we could do something better to avoid this issue.
