### ISSUE TITLE
multipass vms should use the `ubuntu` user

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/multipass#1171]
In lxd, cloud providers, every I can think of, the default login user for a brand new vm or container is `ubuntu`. Shouldn't this also be the case with vms spawned by multipass? Instead, they have the `multipass` user.

**Comment by basak** [comment]
Importantly, if you're preparing an automated deployment that you're testing and developing using multipass, and then deploy it to a public cloud provider, it's likely to break based on some assumption that's different. Wherever possible, multipass should use the same defaults for Ubuntu images as the public clouds do.

**Comment by Saviq** [comment]
That's done in #950, will be part of the imminent release.
