### ISSUE TITLE
Issuing 'stop' on instance that is stopped using 'halt' does not kill the qemu process

### ISSUE THREAD

**Issue by townsend2010** [CanonicalLtd/multipass#1173]
If `halt` is executed inside an instance, multipassd will not notice that the instance is halted since the qemu process does not exit.  Then, if `mutlipass stop` is issued on this instance, `qemu` is still not killed and the instance cannot be started again.

**Comment by townsend2010** [comment]
For the first part of this where the daemon doesn't detect the `halt` inside the instance, from what I've read, `halt` only brings the system to runlevel 0, so `qemu` continues to run and there isn't a qmp event for `multipassd` to detect. As such, there is no way for `multipassd` to update the state for the instance.

For the second part of this, a `stop` issued for the instance, `multipassd` should be able to handle this and kill the `qemu` process and set state to stopped.

**Comment by Saviq** [comment]
So wouldn't this really be #1167? There doesn't seem to be anything that we can do to see that the system halted?

**Comment by ricab** [comment]
Just another data point. I got curious because I could swear I had used something similar and the instance would be seen as stopped. I went looking and indeed, `halt` does less than `poweroff` or `shutdown -h now`, so the daemon sees these last two, but not the first.

**Comment by townsend2010** [comment]
@Saviq, oh right, this is really #1167, just with more detail on how to reproduce the issue.  I forgot about that bug :grin: Anyways, I'll close this as a dup and add some notes there.  Thanks!

@ricab, yep, that's my experience too.  `poweroff` and `shutdown -h now`  actually issue an ACPI poweroff whereas `halt` just puts the OS in runlevel 0.  There are some arguments out there about why `shutdown -h now` and `halt` are treated differently.
