### ISSUE TITLE
Output redirection is broken in Windows

### ISSUE THREAD

**Issue by VariableDeclared** [CanonicalLtd/multipass#1185]
Hey

### Bug Description:

When using multipass in Windows 10 (Build 18363.476) direction does not output to a file or otherwise.

For example `multipass .... > somefile`. Somefile is created but it's blank.
###  Expected Result:

Output from multipass command is written to the file described in the redirection.

### Actual Result:

File is created, but it is created blank.

### Additional Info

Running this on Command Prompt, haven't tried to repeat this on Powershell yet.
Attempted this with `echo "hello" > somefile` and this works.
Also tried redirecting stderr: `2>&1` and `2>somefile.stderr` and `1>somefile.stdout` but I still get the same result.

When redirecting it does not print to the terminal, which is interesting, and removing the redirect casues the output to come back.

Thank you

**Comment by ricab** [comment]
Hi @VariableDeclared, do you observe that with any multipass command, or only with exec? The latter is being tracked in #577, which has a fix coming.

**Comment by VariableDeclared** [comment]
Hey @ricab, my mistake, I didn't find that issue initially. I can confirm it is in fact the same issue, this does not happen on `multipass info` for example. Closing.
