### ISSUE TITLE
clarification on win/mac sources?

### ISSUE THREAD

**Issue by christian-korneck** [CanonicalLtd/multipass#1186]
Hello,

first of all, thanks a lot for this great project and tool!

I tried to figure out how to build multipass on macOS (to chase an issue / suspected bug that I've seen using multipass on my Mac machine), but got the impression that the sources in this repo are "incomplete". I.e. no platform files for Mac/Win, only libvirt backend, etc. Also I couldn't find the build script `build-in-snapshot.sh` referenced in `.travis.yml`.

However, I'm not entirely sure and could be mistaken. Before I dig deeper, could maybe someone who knows more about this project give me a quick heads up? Is my assumption correct that this repo currently does *not* contain all the sources needed to build multipass on macOS and Windows (but only on Linux)?

Many thanks in advance!

**Comment by ricab** [comment]
Hi @christian-korneck , thank you, glad you are enjoying it :smiley: 

You are correct, we indeed keep the macOS- and Windows-specific parts private. Could we help with the issue you are experiencing?

**Comment by christian-korneck** [comment]
hi @ricab, thanks for the clarification, your response has saved me some time.
I'll open a separate issue for my problem shortly.

**Comment by christian-korneck** [comment]
thank you for [open sourcing multipass for all platforms](https://www.phoronix.com/news/Multipass-Fully-Open-Source). ;-)
