### ISSUE TITLE
Unable to read settings: access error

### ISSUE THREAD

**Issue by nelsonghezzi** [CanonicalLtd/multipass#1201]
Hi!

First time trying multipass and encountered this error when trying to read config setting `local.driver`:

```
Unable to read settings: access error (consider running with an administrative role)
```

Even running as admin as it suggests.

Looking at what config file it's trying to read, I've found this:

![image](https://user-images.githubusercontent.com/6424021/69900944-076ced00-1372-11ea-9d61-b90bf434c6c0.png)

Multipass Service is running with Local System account.

**Host:** Windows 10 1909 x64 (OS Build 18363.476)
**Multipass version:** 0.8.0

**Comment by ricab** [comment]
Hi @nelsonghezzi, this really suggests the multipass client somehow is not getting permissions to read the file. 

How did you run multipass as admin? Could you please confirm if it works when right-clicking the PowerShell shortcut, selecting "Run as administrator", and then issuing the multipass command inside?

Also, does the file open if you double-click it? What permissions do you see if you right-click the file, select "Properties", then "Security" tab and click "Advanced"?

**Comment by nelsonghezzi** [comment]
I was previously running from `cmd`, but here is the evidence from an admin PowerShell console:

![image](https://user-images.githubusercontent.com/6424021/70006442-0f40b300-1565-11ea-9333-89311d04e9a8.png)

I ***definitely*** don't have permission into that folder:

![image](https://user-images.githubusercontent.com/6424021/70004366-f1bc1b00-155d-11ea-97ba-648095f03833.png)

![image](https://user-images.githubusercontent.com/6424021/70004383-fbde1980-155d-11ea-9776-2a85aaa358cb.png)

I can't gain access to the folder, but running a command as `System` reveals that the config file is in there (and has 0 bytes in size):

![image](https://user-images.githubusercontent.com/6424021/70006532-70688680-1565-11ea-8dbf-1ecb4f8ad612.png)

Any toughts?

**Comment by nelsonghezzi** [comment]
I just thought of also running `multipass` as `System` and that worked:

![image](https://user-images.githubusercontent.com/6424021/70006940-a4907700-1566-11ea-9f5f-d4ece281de3a.png)

But I'm a bit confused, I was thinking that the multipass daemon (running as a service under the `Local System` account) was trying to access the file, but it seems that is the multipass client program who is.

**Comment by ricab** [comment]
As you found, the daemon only reads settings from disk, it is the client who writes and reads them on the set/get commands. For that, it needs an admin role. At least that is usually enough...

In your case, it seems some folder along that path is owned by the system rather than administrators. That is not a situation we've encountered before, so thanks for alerting us to it. Do you have any idea what could have led to that?

Running `multipass get`/`set` with `psexec -s`, as you did, is the option if you don't want to change permissions. Alternatively, if you think they got messed up and that was not desired, you should be able to add admin back:

1. click change in [the window in your screenshot](https://user-images.githubusercontent.com/6424021/70004383-fbde1980-155d-11ea-9776-2a85aaa358cb.png) (you may need to close other explorer windows and run it with `psexec -i -s explorer.exe`).
2. In the dialog that appears, you can write "Administrators", click "Check Names" to make sure it is valid, and then "OK" out of all properties windows ("Apply" wasn't enough for me)
3. Go back to the same window and add permissions as needed.

**Comment by nelsonghezzi** [comment]
Thanks @ricab.

I didn't remember to voluntarly stepping down permissions on that folder, hence I was reluctant to modify them.

I checked on an old VM with Windows 10 1803 to compare, and found that I **did have** permissions on `C:\Windows\System32\config`, so this might be the default on a fresh Windows install, and that would explain why my scenario is not common.

A weird thing was that I had to manually set permissions on a folder-by-folder basis (i.e.: on config, systemprofile, AppData and Local folders), even though the permissions on the top level folder (config) was set to apply to "This folder, subfolders and files".

Also, I was able to change the owner of these folders without running as SYSTEM (i.e. without `PsExec`), just with my current admin permissions. I'm not Windows Security expert, but that was strange if you ask!

Anyway, I would glad to see an implementation that doesn't require the client app to access the Windows folders directly, but through the daemon.

That way I could harden (now conciously) the security around that particular system folder.

Thanks again, and looking ahead to updates on this product!

**Comment by ricab** [comment]
> A weird thing was that I had to manually set permissions on a folder-by-folder basis (i.e.: on config, systemprofile, AppData and Local folders), even though the permissions on the top level folder (config) was set to apply to "This folder, subfolders and files".

There is a switch in there somewhere to disable permission inheritance. Maybe you (or something on your behalf) did that at some point? If you're unsure, this seems to support the hypothesis of forgotten manual changes :)

> Also, I was able to change the owner of these folders without running as SYSTEM (i.e. without PsExec), just with my current admin permissions. I'm not Windows Security expert, but that was strange if you ask!

Not a Windows expert either, but intuitively I would expect an admin to be able to change what they want in the system. After all, you can run under the system account.

> Anyway, I would be glad to see an implementation that doesn't require the client app to access the Windows folders directly, but through the daemon.
>
> That way I could harden (now conciously) the security around that particular system folder.

We considered that path and decided to keep it open and take a shortcut for now. This way we avoid the impact on IPC and the daemon side. I am not certain where security would weight in that choice, but there may well be other reasons to move to it, like settings validation and remote configs.

Anyway, glad to help and thanks for the feedback.
