### ISSUE TITLE
How do I log in to an instance using ssh?

### ISSUE THREAD

**Issue by zzlxxi** [CanonicalLtd/multipass#1203]
I created a user, but I cannot log in to the instance using ssh with the newly created user.
Error message:
lede@192.168.64.9: Permission denied (publickey).

**Comment by zzlxxi** [comment]
Add a new user lede using the command:
sudo adduser lede

**Comment by Saviq** [comment]
Hi @zzlxxi did you resolve your issues?

Multipass instances are no different to any other machine. Just create a user and import your SSH key.

You may also use `cloud-init` to automate those tasks. See [our documentation for `launch`](https://discourse.ubuntu.com/t/multipass-launch-command/10846) for more.

**Comment by zzlxxi** [comment]
Yes thank you very much！
@Saviq

**Comment by youngdevps** [comment]
It's very simple .follow steps from this article https://techsparx.com/linux/multipass/enable-ssh.html
