### ISSUE TITLE
multipass exec is limited to one word command

### ISSUE THREAD

**Issue by kubiko** [CanonicalLtd/multipass#334]
multipass exec is struggling when more complex command is passed in, for example
`$ multipass exec bionic ls -al ~/`

**Comment by kubiko** [comment]
Actually when I follow lxc syntax here, it seems to be working fine:
`$ multipass exec bionic -- ls -al /home/ubuntu/`

**Comment by Saviq** [comment]
Yes, `--` is how you separate the multipass options from the other ones. You wouldn't need it if there was no `-` in the arguments you used.
