### ISSUE TITLE
Support Ubuntu Desktop Images

### ISSUE THREAD

**Issue by BryanQuigley** [CanonicalLtd/multipass#38]
I'm wondering how hard it would be to launch livecds -as that might not require cloud-init.

Also wondering if this could eventually replace: https://launchpad.net/testdrive for testing.

Obviously, it also might be useful to have cloud-init on desktops to do some automagic.  

I plan to look into these more, but figured if anyone has answers or wants to try them first, have at it :)

**Comment by BryanQuigley** [comment]
Hmm.. uvtools VMs are added through virsh in some way, so they appear virt-manager, making a GUI interface easier.. 

Does this just runs qemu directly?  Which means currently it's not confined even by the default apparmor profiles.

**Comment by Saviq** [comment]
Yes, we're running qemu directly, and indeed they're not confined ATM. We're considering `libvirt` as an alternative, but it has its own caveats (snap confinement is one).

**Comment by townsend2010** [comment]
With libvirt now supported in Multipass and when #249 is merged, it may be possible to launch desktop images.  It will need to be tested, but it may be what is needed to close this.

**Comment by townsend2010** [comment]
Yeah, looks like we need to do something different to support ISO booting as it looks like libvirt didn't like how the defaults were defined with the ISO image.

**Comment by Saviq** [comment]
FWIW libvirt sets graphics up by default I believe, so in that backend it would Just Work™.

**Comment by Saviq** [comment]
The other bit is that we rely on `cloud-init` to set the image up (users, SSH keys and such) so I'm not sure an installation image like Ubuntu Desktop are a match.

I'm going to close this as it doesn't seem to go in the same direction as multipass.
