### ISSUE TITLE
DNSMasqServer does not check if the underlying process has exited

### ISSUE THREAD

**Issue by albaguirre** [CanonicalLtd/multipass#384]
DNSMasqServer does not check if the underlying process has exited.

It should probably throw an exception if it fails to start instead of silent failure, which indirectly makes VM communication fail due to lack of IP.

**Comment by albaguirre** [comment]
Thinking a bit further here.. maybe the current behavior is ok (now that errors form dnsmaqs are logged) but perhaps enhanced error messaging to the user would be useful.

**Comment by townsend2010** [comment]
I think this is basically the same issue as #325, so I'm going to close this a dup of that one.
