### ISSUE TITLE
bridge missing after reboot

### ISSUE THREAD

**Issue by marosg42** [CanonicalLtd/multipass#435]
I am using libvirt driver. After host was rebooted, previously working instance could not be started. Changing driver to qemu and then back to libvirt helped

> Saviq: clipped for interesting content
```
Oct 08 17:44:19 tango libvirtd[32384]: operation failed: network 'default' already exists with uuid 5006fcf4-9b47-4288-8eab-1ed1fc8a443b
Oct 08 17:44:49 tango libvirtd[32384]: Failed to create symlink '/var/snap/multipass/common/libvirt/qemu/networks/autostart/default.xml' to '/var/snap/multipass/common/libvirt/qemu/networks/default.xml': File exists
```

**Comment by Saviq** [comment]
Looks like this is a one-time upgrade issue. We now delete and recreate the `libvirt` network as multipassd stops and starts. You upgraded and the network was there, when you restarted multipass again it was removed and recreated.
