### ISSUE TITLE
Multipass prompts for statistics from within snapcraft

### ISSUE THREAD

**Issue by kyrofa** [CanonicalLtd/multipass#438]
Beyond ensuring it's installed, snapcraft tries to keep Multipass as an implementation detail. However, on first run, Multipass interrupts the build process by asking the user to submit usage statistics, which is a bit confusing coming from snapcraft. Is there a way to suppress this inquiry when running from within snapcraft?

**Comment by Saviq** [comment]
We [do check](https://github.com/CanonicalLtd/multipass/blob/master/src/client/cmd/launch.cpp#L184) if we're running in an interactive terminal and skip that prompt if not, so you should be able to suppress it that way?

**Comment by sergiusens** [comment]
Does it show when running shell or execute?

**Comment by Saviq** [comment]
No, only on `launch`.
