### ISSUE TITLE
provide `multipass shell -root`

### ISSUE THREAD

**Issue by sergiusens** [CanonicalLtd/multipass#441]
It would be nice if we could just straight out shell in or execute commands as the root user.

**Comment by Saviq** [comment]
This would be a simple wrapper around `sudo`, think it's worth it? Do we then support `multipass shell --user <name>`, too?

**Comment by Saviq** [comment]
I'm scoping this out.

**Comment by winkeesail** [comment]
How can I log in as a root user? when I execute multipass shell primary, I logged in as user "ubuntu".

**Comment by townsend2010** [comment]
Hey @winkeesail,

To log in directly as `root`, `multipass exec primary -- sudo bash` will do the job.

**Comment by winkeesail** [comment]
> Hey @winkeesail,
> 
> To log in directly as `root`, `multipass exec primary -- sudo bash` will do the job.

Thanks so much, you help a lot!
