### ISSUE TITLE
delete failed: OS Error

### ISSUE THREAD

**Issue by kstenerud** [CanonicalLtd/multipass#466]
OS: Ubuntu 18.04

snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     beta
refresh-date: today at 11:28 CET
channels:                                      
  stable:    –                                 
  candidate: –                                 
  beta:      2018.10.1             (461) 104MB classic
  edge:      2018.10.1-16-gcb03105 (483) 105MB classic
installed:   2018.10.1             (461) 104MB classic

Steps:

    $ multipass launch --name host
    $ multipass exec host bash
    (install a bunch of stuff)
    (note: I think I filled up the virtual drive in the process)
    $ multipass delete -p host
    [2018-11-01T12:18:10.332] [error] [host] process error occurred Crashed
    
    delete failed: OS Error

Logs:

/var/log/kern.log:

	Nov  1 12:18:10 tp-work kernel: [147600.302431] Code: 55 48 89 f5 53 48 89 fb 48 8d bf 80 00 00 00 e8 4a 68 01 00 48 8d 7b 48 49 89 c4 48 89 ee e8 3b 7b 01 00 49 8b 3c 24 48 89 c5 <48> 8b 07 ff 50 28 48 89 df 89 85 88 00 00 00 5b 5d 41 5c e9 ac e3 

/var/log/apport.log:

	ERROR: apport (pid 18125) Thu Nov  1 12:18:10 2018: called for pid 8669, signal 11, core limit 0, dump mode 1
	ERROR: apport (pid 18125) Thu Nov  1 12:18:10 2018: executable: /snap/multipass/461/bin/multipassd (command line "/snap/multipass/461/bin/multipassd")
	ERROR: apport (pid 18125) Thu Nov  1 12:18:10 2018: executable does not belong to a package, ignoring

/var/log/syslog:

	Nov  1 12:17:09 tp-work multipassd[8669]: VM powering down
	Nov  1 12:17:39 tp-work multipassd[8669]: attempting to release non-existant addr: 52:54:00:55:54:d4
	Nov  1 12:17:39 tp-work avahi-daemon[251]: Interface tap-6ebcc3c5f09.IPv6 no longer relevant for mDNS.
	Nov  1 12:17:39 tp-work avahi-daemon[251]: Leaving mDNS multicast group on interface tap-6ebcc3c5f09.IPv6 with address fe80::e4b4:deff:fe31:d142.
	Nov  1 12:17:39 tp-work systemd-networkd[122]: tap-6ebcc3c5f09: Lost carrier
	Nov  1 12:17:39 tp-work dnsmasq[8803]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[8803]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work kernel: [147569.765453] mpqemubr0: port 2(tap-6ebcc3c5f09) entered disabled state
	Nov  1 12:17:39 tp-work dnsmasq[1225]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using local addresses only for domain lxd
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[8803]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[8803]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[8803]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[8803]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[8803]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[8803]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work avahi-daemon[251]: Withdrawing address record for fe80::e4b4:deff:fe31:d142 on tap-6ebcc3c5f09.
	Nov  1 12:17:39 tp-work systemd-networkd[122]: mpqemubr0: Lost carrier
	Nov  1 12:17:39 tp-work dnsmasq[1225]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using local addresses only for domain lxd
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[843]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[843]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[843]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[843]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[1225]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using local addresses only for domain lxd
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[843]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[843]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[8803]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[8803]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work dnsmasq[1225]: reading /etc/resolv.conf
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using local addresses only for domain lxd
	Nov  1 12:17:39 tp-work dnsmasq[1225]: using nameserver 127.0.0.53#53
	Nov  1 12:17:39 tp-work NetworkManager[296]: <info>  [1541071059.8446] device (tap-6ebcc3c5f09): released from master device mpqemubr0
	Nov  1 12:17:39 tp-work multipassd[8669]: VM powering down
	Nov  1 12:18:09 tp-work multipassd[8669]: QProcess: Destroyed while process ("qemu-system-x86_64") is still running.
	Nov  1 12:18:10 tp-work multipassd[8669]: process error occurred Crashed
	Nov  1 12:18:10 tp-work kernel: [147600.302431] Code: 55 48 89 f5 53 48 89 fb 48 8d bf 80 00 00 00 e8 4a 68 01 00 48 8d 7b 48 49 89 c4 48 89 ee e8 3b 7b 01 00 49 8b 3c 24 48 89 c5 <48> 8b 07 ff 50 28 48 89 df 89 85 88 00 00 00 5b 5d 41 5c e9 ac e3 
	Nov  1 12:18:10 tp-work systemd[1]: system-apport\x2dforward.slice: Failed to reset devices.list: Operation not permitted
	Nov  1 12:18:10 tp-work systemd[1]: Starting Apport crash forwarding receiver...
	Nov  1 12:18:10 tp-work systemd[1]: snap.multipass.multipassd.service: Main process exited, code=dumped, status=11/SEGV
	Nov  1 12:18:10 tp-work systemd[1]: Started Apport crash forwarding receiver.
	Nov  1 12:18:40 tp-work systemd[1]: snap.multipass.multipassd.service: State 'stop-sigterm' timed out. Killing.
	Nov  1 12:18:40 tp-work systemd[1]: snap.multipass.multipassd.service: Killing process 8803 (dnsmasq) with signal SIGKILL.
	Nov  1 12:18:40 tp-work systemd[1]: snap.multipass.multipassd.service: Failed with result 'core-dump'.
	Nov  1 12:18:41 tp-work systemd[1]: snap.multipass.multipassd.service: Service hold-off time over, scheduling restart.
	Nov  1 12:18:41 tp-work systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 1.
	Nov  1 12:18:41 tp-work systemd[1]: Stopped Service for snap application multipass.multipassd.
	Nov  1 12:18:41 tp-work systemd[1]: snap.multipass.multipassd.service: Failed to reset devices.list: Operation not permitted
	Nov  1 12:18:41 tp-work systemd[1]: Started Service for snap application multipass.multipassd.
	Nov  1 12:18:41 tp-work multipass.multipassd[18218]: E1101 12:18:41.778676777   18218 uri_parser.cc:46]           bad uri.scheme: ''
	Nov  1 12:18:41 tp-work multipass.multipassd[18218]: E1101 12:18:41.778701651   18218 uri_parser.cc:52]                            ^ here
	Nov  1 12:18:41 tp-work multipass.multipassd[18218]: E1101 12:18:41.778706912   18218 http_proxy.cc:54]           cannot parse value of 'http_proxy' env var
	Nov  1 12:18:41 tp-work multipassd[18218]: gRPC listening on unix:/run/multipass_socket, SSL:on
	Nov  1 12:18:41 tp-work dnsmasq[18281]: started, version 2.75 cachesize 150
	Nov  1 12:18:41 tp-work dnsmasq[18281]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
	Nov  1 12:18:41 tp-work dnsmasq-dhcp[18281]: DHCP, IP range 10.64.70.2 -- 10.64.70.254, lease time infinite
	Nov  1 12:18:41 tp-work dnsmasq-dhcp[18281]: DHCP, sockets bound exclusively to interface mpqemubr0
	Nov  1 12:18:41 tp-work dnsmasq[18281]: reading /etc/resolv.conf
	Nov  1 12:18:41 tp-work dnsmasq[18281]: using nameserver 127.0.0.53#53
	Nov  1 12:18:41 tp-work dnsmasq[18281]: read /etc/hosts - 5 addresses
	Nov  1 12:18:41 tp-work dnsmasq[18281]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
	Nov  1 12:21:47 tp-work systemd-resolved[168]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.

**Comment by townsend2010** [comment]
@kstenerud,

Thanks for the report.  What is looks like here is that the instance would not shutdown in the 30 seconds that is given before `SIGKILL` is sent to the qemu process. hat is not clear is why `multipassd` crashed right after this.  I'll need to look into that...

**Comment by Saviq** [comment]
Please reopen if you encounter this again.
