### ISSUE TITLE
When mouting over instance user's home directory, `mount` hangs

### ISSUE THREAD

**Issue by hatched** [CanonicalLtd/multipass#47]
Ubuntu: 16.04.04
multipass: 2017.2.2

```
multipass launch -n charmtool
mkdir charmtool
multipass mount remote:/home/hatched/charmtool charmtool:/home/ubuntu
```
Now `multipass list` won't return, after `^C` but `multipass help` does.

Restarting the host returns this back to the state before the mount was run.

**Comment by Saviq** [comment]
This suggests the daemon went bad. FWIW you don't need the `remote:` prefix (we're thinking of reworking that part actually).

It might've been too early, `sshfs` might not have been installed on the machine yet. Can you try with the `edge` channel? Also not I saw on IRC you were using relative paths (or tilde, at least) for the target, that might not work.

**Comment by hatched** [comment]
After upgrading to `edge` it still exhibits the same issue.

**Comment by townsend2010** [comment]
Is the mount command itself hanging, like it never returns and you are issuing list in another terminal?

Also, you are mounting over the ubuntu user's home directory.  Is this what you want?  I wonder if that is playing havoc with ssh keys and somehow sshfs is bombing out in the VM which we are not catching.

**Comment by hatched** [comment]
I'm hitting ^C and running list in the same terminal.

I'm trying to mount the containers ~ to a folder on the host. Am I doing that incorrectly? Aiui from the help output is that the host goes first.

**Comment by townsend2010** [comment]
By container, do you mean the VM or is this like an LXD container you are trying to mount inside the VM?

Also, yes, /home/hatched/charmtool on the host is going to be mounted in the VM at /home/ubuntu the way you have it.  If you are not intending to mount over the VM ubuntu user's full home directory, perhaps doing something like

``
multipass mount  /home/hatched/charmtool charmtool:/home/ubuntu/charmtool
``

is what you are after.  This will create a 'charmtool' directory in the VM 'ubuntu' user's home directory and mount the host's charmtool directory there.

**Comment by hatched** [comment]
Sorry, yes VM.
That worked! Thanks!

So it looks like there is some issue with mounting the user directory on the VM.

**Comment by townsend2010** [comment]
Cool!

Yeah, so what I suspect is that when mounting over the user directory in the VM, the ssh key goes missing which is causing havoc for sshfs and our custom sftp server.  So for now, we may need to sanitize allowing the home directory itself as being a target which would be related to #17.

However, I could see legitimate cases for allowing /home/$USER to be a target such as mounting a full home on the host to a full home in the VM.

**Comment by townsend2010** [comment]
I think the solution for now is not allow mounts over /home/ubuntu.  That said, I'm going to close this particular bug with reference to #17 which has a PR up and includes a fix to not allow /home/ubuntu.
