### ISSUE TITLE
[snap] Can't change driver when there's no instances

### ISSUE THREAD

**Issue by Saviq** [CanonicalLtd/multipass#476]
```
$ multipass list
No instances found.
$ snap set multipass driver=QEMU
error: cannot perform the following tasks:
- Run configure hook of "multipass" snap (run hook "configure":
-----
All instances need to be in the stopped state.
Please save any data, and then stop them before proceeding.
-----)
```

Looks like the check for stopped instances has gone wrong.

**Comment by townsend2010** [comment]
@Saviq 

Strange, this works fine for me.  I tried this using multipass from edge.

I also tried running what the script does manually as well and that worked.  I'm not sure what is going on with your setup...

**Comment by Saviq** [comment]
Oh hmm, can't reproduce now either. Will reopen if I do.
