### ISSUE TITLE
build steps for the entire macOS package

### ISSUE THREAD

**Issue by mdaniel** [CanonicalLtd/multipass#554]
This is kind of related to #497 but is for sure not about the README. I want to be able to build a "release similar" `.pkg` archive on my machine.

There appears to be [a shell script](https://github.com/CanonicalLtd/multipass/blob/2018.12.1/.travis.yml#L80) used to build what I presume is the macOS `.pkg`, but that script is apparently locked up inside [the encrypted tar](https://github.com/CanonicalLtd/multipass/blob/2018.12.1/.travis.yml#L69). I can appreciate the need to have secrets available for travis, but I would be interested in helping in any way that I can to decouple the _secrets_ from the _build script_ so we can then make those steps more widely available.

**Comment by Saviq** [comment]
Hi, we're keeping the macOS parts of Multipass proprietary at the moment. Could we help in any other way?

**Comment by mdaniel** [comment]
Would you accept a PR that updated the readme to clarify that position, to keep folks like me from expecting to be able to build the project for macOS? Something like:

> For macOS we provide installers on GitHub.
>
> At this time, the source for the macOS `.pkg` is proprietary. While it is possible to compile multipass for macOS, the resulting binaries will not behave like the installers that are provided.

---

Separately, it makes me sad that Canonical would do such a thing. I'm pretty sure that if those `.pkg` files came from `ubuntu.com/multipass-enterprise/multipass-2018.12.1-full-Darwin.pkg` (or whatever), then I wouldn't have even considered opening this ticket. It would have correctly communicated that the macOS bits are not open source and no one should expect otherwise.
