### ISSUE TITLE
Support for static IP address

### ISSUE THREAD

**Issue by dmarkey** [CanonicalLtd/multipass#567]
Hi,

Is it possible to specify the IP address for the VM on OSX?

**Comment by dmarkey** [comment]
I'm using multipass with microk8s and for development it's very nice to have a stable or supplied IP address.

**Comment by Saviq** [comment]
May I ask what's your workflow? How often do you recreate the instance? It currently isn't supported for the instance to have a static IP, but it should be possible with [`cloud-init`](https://cloudinit.readthedocs.io/en/latest/) to add a second IP to the main interface. That should help you get a static IP that the instance would be available on.

**Comment by Saviq** [comment]
Hi @dmarkey, please reopen this if you have anything to add.

**Comment by NerdsvilleCEO** [comment]
@Saviq if I may chime in, I am planning on using multipass to host a docker host for example which IntelliJ (or another editor) would use docker to send code to a remote interpreter for IDE specific features.

What would be the easiest way to maintain this without having to create and manually copy over the IP address and change if it updates?

**Comment by k33g** [comment]
I would like to rekindle this issue. Most of the time I use VirtualBox on OSX + Vagrant and I add this in my `Vagrantfile`:

```ruby
    node.vm.network "private_network", ip: "172.16.245.240"
```

and it's useful for me (as I'm using several VMs at the same time) because I can "give" a domain name to every VM in my `hosts` file (on OSX)

```
172.16.245.240 microk8s.test
```

**Comment by sanderhahn** [comment]
Made a small utility that uses the output of `multipass list --format json` to update the `/etc/hosts` file: https://github.com/sanderhahn/multipass-hosts

**Comment by mconner** [comment]
> May I ask what's your workflow? How often do you recreate the instance? It currently isn't supported for the instance to have a static IP, but it should be possible with some [`cloud-init`](https://cloudinit.readthedocs.io/en/latest/) trickery to add a second IP to the main interface. That should help you get a static IP that the instance would be available on.

Could you provide an example of the cloud-init trickery you speak of?

**Comment by Saviq** [comment]
> Could you provide an example of the cloud-init trickery you speak of?

That would actually be [netplan](https://netplan.io/examples/) trickery. Create `/etc/netplan/90-static.yaml` with something like the following:
```yaml
network:
    ethernets:
        enp5s0:
            addresses:
            - 10.10.10.10/24
    version: 2
```

**Comment by derekssmith** [comment]
I have a use case for this feature.  We use `microk8s` for development and run it on our laptops, then we setup a DNS zone that results in the IP address of the VM.  If we cannot control the IP address of the VM, this breaks down because everyone will need different IP.  I would prefer not to have to manage local `hosts` files for this to work.

**Comment by yingshaoxo** [comment]
If you are using windows10, you should check a file which called `hosts.ics` under `C:\Windows\System32\drivers\etc`

```
# Copyright (c) 1993-2001 Microsoft Corp.
#
# This file has been automatically generated for use by Microsoft Internet
# Connection Sharing. It contains the mappings of IP addresses to host names
# for the home network. Please do not make changes to the HOSTS.ICS file.
# Any changes may result in a loss of connectivity between machines on the
# local network.
#

192.168.234.66 primary.mshome.net # 2020 10 3 28 6 34 15 247
192.168.234.65 Thinkpad-yoga260.mshome.net # 2025 10 1 20 6 34 15 24
```



It says I could use `http://primary.mshome.net/` to visit my ubuntu instance. Here, for example, I use it to visit the jupyter-notebook inside ubuntu: http://primary.mshome.net:8888/tree

**Comment by ml4** [comment]
@Saviq I would also like a static IP on my guest ubuntu VM on macos Ventura; I am migrating almost my entire dev env into ubuntu and coding via vscode ssh, so will need a network address that is fixed for that.  I will also be using a browser on my mac to surf to the apps on the ubuntu guest, so would like to add the machine to my internal DNS.  As I rebuild the guest not infrequently in order to ensure I have a script which deploys exactly what I need, the netplan trickery I will try.  But I note the route add you added appears to add a new /24 to the host - I presume I can add this guest to the same /24 I have all my RFC1918 nodes on so it just becomes another box on my internal network?  I may have a need for physicals in that network to access the guest on my mac. Thanks

**Comment by ricab** [comment]
Hi @ml4, you don't need *QEMU and virtualbox*, they are alternatives. Multipass supports additional network interfaces on either one. This may be of interest to you: https://multipass.run/docs/configure-static-ips

**Comment by johnmanko** [comment]
I'd like to chime in here.

Multipass is supposed to be cross platform, but this is one area in which it breaks down.  I've got a team of developers, each with different environments (Linux, MacOS, Windows!).   I was in the process of creating scripts and `cloud-init` files to bring up vms for a k8s master+nodes cluster on developer machines - ie, making the process easy for them.  Having host-network static IPs is needed.  Now each developer needs to have knowledge on how to modify the host routing/networking - knowledge some just don't have.  I really like multipass, but I just wish more effort went into networking.

**Comment by townsend2010** [comment]
Hi @johnmanko!

There are many different ways one could have their host networks configured and it would be very dangerous for Multipass to have to make assumptions about the host networking and potentially break it and render the host unable to use the network.  I don't think it would be possible to account for all the different set ups that *could* exist.  We do set up a default NAT'd networked on each platform which is enough for most use cases, but I don't really see a way we could set up special use case networks.

That said, could you please describe a bit further on how the host routing/networking is needing to be modified for your use cases?  Perhaps there is something we haven't considered.

**Comment by johnmanko** [comment]
@townsend2010 

Hello.  Well, there's nothing special about my use case.  Fire up a multi-node Kubernetes cluster for local development testing.  A host-accessible and host-private network with static IPs is a required, similar to what I have [here](https://github.com/johnmanko/vagrant-k8s-cluster).  Multipass is already (mostly) cross platform, and I'd much rather give it a try in my testing than VirtualBox.  

Thanks.

**Comment by townsend2010** [comment]
Hi @johnmanko,

Ah, ok, I understand your use case.  You would basically like how our current default NAT'd network works except have static IP's and not DHCP.  I think this would be fairly straightforward on Linux, but Windows and macOS is certainly a whole different story- they don't make it easy to do this programmatically.  It's not impossible, but it would be a pretty large engineering effort IMO.

That said, given we'd like to better support Kubernetes and Docker clusters, this is something we should give more consideration to.  I'll add it to our feature backlog.

**Comment by johnmanko** [comment]
@townsend2010 

Hello again. Just wondering if there is a Github issue I can following regarding a proposed enhancement.  I searched the open issues and couldn't find anything.

Thanks.

**Comment by sktripamer** [comment]
I've made a quick little utility NPM package for MacOS to route Multipass instance names to permanently accessible local domains.

```
npm install -g @sktripamer/unifypass
sudo unifypass start
```

Now you can access http://multipass-instance-name.multipass


By default it works with 80 and 443 with SSL passthrough. You can add more ports with:

```
sudo unifypass start --ports 8010,8020,8030
```

It works by creating a DNS server for the .multipass domain and forwarding it to the loopback address (127.0.0.1) where we have a reverse proxy getting the local network IP with 'multipass list', meaning it's very responsive to any changes on the DHCP leases or any changes to multipass instances.

Sudo is needed to create the DNS server and listen on ports 80 and 443.

Haven't tested all the features, but the basic start and stopping with the --ports flags seems to work, and I needed it for my own work, so deciding to publish now. Feel free to try to use and come back with any issues.

**Comment by giuliazanchi** [comment]
Hi @sktripamer , thanks for your comment! If it's OK for you, we'd like share this information on the Multipass Discourse forum in the [Community Knowledge category](https://discourse.ubuntu.com/c/multipass/community-knowledge/267), a new area of our forum where we are trying to collect community-provided workarounds, tips and tricks. I can cross-post it there for you and tag you if you like, or if you have editing rights, please go ahead and share it over there. Either way, let us know :)

**Comment by giuliazanchi** [comment]
Hi again @sktripamer , I've created a new topic in our Community Knowledge with your content, here: https://discourse.ubuntu.com/t/route-multipass-instance-names-to-permanently-accessible-local-domains/50570

P.s. If you comment on that post, or let me know your username on Discourse, I can tag you properly :)
