### ISSUE TITLE
Launch failure: multipass for Windows

### ISSUE THREAD

**Issue by wol190** [CanonicalLtd/multipass#570]
I was very interested to see the article announcing multipass for Windows, but I'm having trouble launching:
```
>multipass launch
launch failed: timed out waiting for instance to respond

>multipass list
Name                    State             IPv4             Release
assuring-tardigrade     UNKNOWN           --               Ubuntu 18.04 LTS
```
I have multipassd running from a separate command shell. I'm on a domain network, using Windows 10 (Enterprise, Version 10.017134 OS Build 17134. Hardware Abstraction Layer Version 10.0.17134.471 - which maps to Version 1803). Do I need to somehow include multipass as an Allowed application?

**Comment by wol190** [comment]
@Saviq Many thanks for the quick response. It turns out that although my machine is on Version 1803 it wasn't on a new enough Hardware Abstraction Layer Version. After a Windows update (taking me to Hardware Abstraction Layer Version 10.0.17134.556) and then a reinstall of multipass, multipass is now working fine, which is great!

**Comment by Saviq** [comment]
@wol190 glad to hear, we should improve our installer checks then :)
