### ISSUE TITLE
Multipass for Windows instance cannot resolve hostnames

### ISSUE THREAD

**Issue by marksztainbok-okta** [CanonicalLtd/multipass#572]
I just installed the beta of the Windows Multipass and set up an instance and found that it cannot resolve hostnames.

When I attempted to resolve a hostname, I'm getting an error similar to this:
```
multipass@dev:~$ ping www.google.com
ping: www.google.com: Temporary failure in name resolution
```

It's not a network connectivity issue as if I use an IP address I can successfully communicate:
```
multipass@dev:~$ ping 216.58.195.68
PING 216.58.195.68 (216.58.195.68) 56(84) bytes of data.
64 bytes from 216.58.195.68: icmp_seq=1 ttl=56 time=24.0 ms
64 bytes from 216.58.195.68: icmp_seq=2 ttl=56 time=24.6 ms
64 bytes from 216.58.195.68: icmp_seq=3 ttl=56 time=24.6 ms
^C
--- 216.58.195.68 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 24.020/24.430/24.636/0.316 ms
```

I configured instance using the 18.04.1 image  and am running Windows 10 Enterprise version 10.0.17763 N/A Build 17763.

My resolv.conf in the instance contains the folllowing:
```
nameserver 127.0.0.53
search mshome.net
```

Any ideas what could be wrong and how to fix it?

**Comment by townsend2010** [comment]
Hi @marksztainbok-okta,

Thank you for reporting this issue.  Are you running a firewall?  If so, perhaps you need to allow instances access to DNS?  But it certainly seems like *something* is blocking DNS lookup on the virtual network.

**Comment by Saviq** [comment]
`127.0.0.53` is the local DNS caching server of `systemd-resolve`. To see the actual upstream DNS server, you can use `systemd-resolve --status` inside the instance - look for something similar to:

```
  Current DNS Server: 10.2.0.1
         DNS Servers: 10.2.0.1
```

Can you try pinging the address listed there? Also, the equivalent of `dig google.com @10.2.0.1`? Try with TCP using `dig +tcp google.com @10.2.0.1`?

**Comment by Saviq** [comment]
That's likely the culprit then, your Windows DHCP didn't give your instance a DNS address... Can you check and launch any other VM manually with the Hyper-V manager, connect it to the Default Switch and see if you get a happy network?

**Comment by debsahu** [comment]
same issue here.

**Comment by debsahu** [comment]
Manually edited **/etc/resolv.conf** with cloudfare DNS `nameserver 1.0.0.1` and everything is working now.

**Comment by townsend2010** [comment]
By chance, is anyone here using Docker Linux Containers on Windows (LCOW)?  Having that running affects non-Docker VM's from having a usable DNS provided by the Hyper-V default switch.

See https://github.com/minishift/minishift/issues/1792#issuecomment-353541676 and https://github.com/docker/for-win/issues/1166#issuecomment-340062138.

**Comment by marksztainbok-okta** [comment]
Yeah I do have Docker for Windows installed and running

**Comment by marksztainbok-okta** [comment]
This is the log:
```
E0124 11:29:43.891000000 32384 server_secure_chttp2.cc:84] {"created":"@1548358183.891000000","description":"No address added out of total 2 resolved","file":"..\3rd-party\grpc\src\core\ext\transport\chttp2\server\chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1548358183.891000000","description":"Failed to add port to server","file":"..\3rd-party\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1548358183.891000000","description":"OS Error","file":"..\3rd-party\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":201,"os_error":"An attempt was made to access a socket in a way forbidden by its access permissions.\r\n","syscall":"bind","wsa_error":10013}]},{"created":"@1548358183.891000000","description":"Failed to add port to server","file":"..\3rd-party\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1548358183.891000000","description":"OS Error","file":"..\3rd-party\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":201,"os_error":"An attempt was made to access a socket in a way forbidden by its access permissions.\r\n","syscall":"bind","wsa_error":10013}]}]}
error: Failed to start multipass gRPC service at localhost:50051
```

It looks like it is a similar issue

**Comment by townsend2010** [comment]
@marksztainbok-okta,

Yep, I think either Docker or Hyper-V has reserved that port:(

For a temporary workaround, you can set the `server-address` option in `multipassd` and set the `MULTIPASS_SERVER_ADDRESS` for client to get it working like in the aforementioned bug report.

Sorry about all of this frustration, but it's good to know what the issues are.

**Comment by marksztainbok-okta** [comment]
I tried the workaround but after it started `multipassd` and I do a `multipass ls` I no longer see the instance I had created. The instance is started and running in Hyper-V.

I tried restarting the VM but `multipass ls` is still reporting `No instances found`

**Comment by marksztainbok-okta** [comment]
I did not. It's the same installation. It seems like there should be a way to reattach an instance to the database in this case. Because of the DNS issue I hadn't configured the instance yet but I would have been exceptionally annoyed if I had invested time in configuring it and then found I couldn't access it.

**Comment by townsend2010** [comment]
Ah, ok, I think I know why it's not showing up in multipass.  It's because the original instance was created when `multipassd` was running as a system service and so it stored the database in a different place than when running it manually due to the pathing of the environment.

Perhaps modifying the multipassd system service to use the `address` option may fix this.

**Comment by marksztainbok-okta** [comment]
I changed the service command line to `"C:\Program Files\Multipass\bin\multipassd.exe" --address localhost:5001 /svc`. The service starts and I can see in the event log that it binds to port 5001. However the Windows SCM does not recognize that the service started and get an error that it didn't respond in a timely manner and Windows kills it ☹️

**Comment by townsend2010** [comment]
Good grief...I'll look into if there is way to make that work.

**Comment by townsend2010** [comment]
Ok, I was able to make it work by doing the following:

1. Stop the Multipass service.
2. Open the Multipass Service Properties.
3. Under `Start parameters` near the bottom of the window, add `--address localhost:5001` (or whatever port).
4. Start the service.

I did this and now have `multipassd` running as a service listening on port 5001.  Hopefully this will work for you.

**Comment by townsend2010** [comment]
Another bug report supporting the DNS issue and Docker:
https://github.com/docker/for-win/issues/1166#issuecomment-425696267

**Comment by marksztainbok-okta** [comment]
> Ok, I was able to make it work by doing the following:
> 
> 1. Stop the Multipass service.
> 2. Open the Multipass Service Properties.
> 3. Under `Start parameters` near the bottom of the window, add `--address localhost:5001` (or whatever port).
> 4. Start the service.
> 
> I did this and now have `multipassd` running as a service listening on port 5001. Hopefully this will work for you.

This doesn't work for me. The service looks like it starts successfully but then stops for some reason. The services UI says it is Running but if you refresh then it isn't again.

**Comment by ricab** [comment]
A bit of a shot in the dark, but do you have an internet connection when that happens? Because we currently have an open bug where multipassd fails to start when it can't access image hosts: #555

**Comment by ricab** [comment]
@marksztainbok-okta can you please also include `-V debug` in the `Start parameters`?

**Comment by marksztainbok-okta** [comment]
I do have an internet connection at the time I'm starting multipassd.

I've added the parameter. Does it produce logs somewhere I can look to see what the issue is?

**Comment by ricab** [comment]
Yes, you can access them in the Event Viewer, under "Windows Logs->Application"

**Comment by marksztainbok-okta** [comment]
No it says the service started but then it didn't.

**Comment by townsend2010** [comment]
Hmm, I'm not really sure what's going on at this point.  `multipassd --address localhost:5001` will still start manually, but not start fully when adding the `--address localhost:5001` to the `Start parameters`?

**Comment by marksztainbok-okta** [comment]
That is correct

**Comment by Saviq** [comment]
We've not seen this in a while, please reopen if you have this issue still.

**Comment by pcgeek86** [comment]
This ought to fix it. Don't modify `/etc/resolv.conf` directly, per the built-in docs.

```
sudo netplan set ethernets.eth0.nameservers.addresses=[8.8.8.8,8.8.4.4]
sudo netplan apply
```

**Comment by iwnow** [comment]
> This ought to fix it. Don't modify `/etc/resolv.conf` directly, per the built-in docs.
> 
> ```
> sudo netplan set ethernets.eth0.nameservers.addresses=[8.8.8.8,8.8.4.4]
> sudo netplan apply
> ```

it's works, thank you! @pcgeek86

**Comment by boistordu** [comment]
So multipass for windows, whether it's virtualbox or hyper-V, can't rely on the dns client from windows itself to serve it dns resolution? 
If that's the case, it would be nice to put it in the documentation
