### ISSUE TITLE
Ubuntu Core 18 timeout when launched

### ISSUE THREAD

**Issue by tonyespy** [CanonicalLtd/multipass#601]
multipass launch times out if given the URL to the latest stable Ubuntu Core 18 image (see below).

This has been reproduced with the latest versions of the multipass snap (v0.5 & v0.5-14-gd5dcc13) on Ubuntu 18.04 LTS.

Here's the command run, and its output:

> $ multipass launch http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz
> launch failed: timed out waiting for instance to respond

**Comment by ricab** [comment]
I confirm this. For future reference, the timeout happens when the instance is already starting, not while downloading the image. Issuing a `multipass list` then produces:

```
$ multipass list
[2019-02-11T09:50:49.883] [error] [daemon] Error fetching image information: Unable to find an image matching hash "4a4734c2e8b1d08b97ce9d4da6ed40f134b1936897fb6341dd16afa2f6d91aaf"

Name                    State             IPv4             Release
jesting-starling        UNKNOWN           --               Not Available
```

Trying to stop the issue, I get, after a while
```
$ multipass stop jesting-starling
Stopping jesting-starling - [2019-02-11T09:52:56.829] [error] [jesting-starling] process error occurred Crashed
$ multipass list                                                              
[2019-02-11T09:54:13.229] [error] [daemon] Error fetching image information: Unable to find an image matching hash "4a4734c2e8b1d08b97ce9d4da6ed40f134b1936897fb6341dd16afa2f6d91aaf"

Name                    State             IPv4             Release
jesting-starling        STOPPED           --               Not Available
```

**Comment by Saviq** [comment]
I'm having trouble booting this image under QEMU in the first place, it gets stuck for me after

```
[   14.167659] [drm] Initialized qxl 0.1.0 20120117 for 0000:00:02.0 on minor 0
[   14.172953] tsc: Refined TSC clocksource calibration: 2394.455 MHz
[   14.174212] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x2283c1579c6, max_idle_ns: 440795259439 ns
[   14.662771] usbcore: registered new interface driver usb-storage
[   14.675136] sdhci: Secure Digital Host Controller Interface driver
[   14.676471] sdhci: Copyright(c) Pierre Ossman
[   34.143772] random: fast init done
[   46.090651] random: crng init done
```

@tonyespy were you able to boot it in KVM at all?

At some point I got it to fail at
```
findfs: unable to resolve ´LABEL=writable´
done.
cannot find ´writable´ partition
```

**Comment by tonyespy** [comment]
I was able to boot it in kvm on a host running 18.04 (under Parallels). The first time I tried it, it seemed to hang while re-sizing the writeable partition. I've tried several times since then with no problems; it boots OK and console-conf comes up super-fast.

**Comment by Saviq** [comment]
@tonyespy I tried this again and while the instance launched (ssh is answering), it doesn't run `cloud-init`:

```
$ cloud-init status
status: disabled
```

@michaelvogt is this on purpose? Is there a way to enable `cloud-init` on the stock core18 images?

**Comment by Saviq** [comment]
This seems fixed now:
```
$ multipass launch http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz
Launched: touted-woodcreeper
$ multipass shell touted-woodcreeper
multipass@touted-woodcreeper:~$
```

**Comment by Saviq** [comment]
Marking _invalid_ as it's not a Multipass issue.
