### ISSUE TITLE
Multipass loses snapcraft project mount when unpacked squashfs is within

### ISSUE THREAD

**Issue by evandandrea** [CanonicalLtd/multipass#652]
I was consistently getting snapcraft failures when building an updated bitcoin snap. This was strange - any other snap was building fine. Digging further I could see that the VM spun up by multipass was losing the mount of the snapcraft project directory. I noticed I had a unpacked snap squashfs in the project directory and this was getting staged in. Running the build without this directory tree under the project dir results in a successful build. Running the build with this directory tree results in multipass losing the mount. 🤷‍♂️

Here's the tail end of a successful build and then reproducing the failure. Happy to provide a tarball of the project dir if that helps.

https://gist.github.com/evandandrea/f7a5b500cf5bc02363f0914212e20dd6

**Comment by Saviq** [comment]
Hey @evandandrea, what version of Multipass? Can you try https://github.com/CanonicalLtd/multipass/releases/tag/v0.6.0-pre1 please? I believe this got fixed since the last release.

**Comment by evandandrea** [comment]
Indeed, this worked. I take it that version will hit cask at some point?

**Comment by Saviq** [comment]
@evandandrea yes, we're pushing it to cask on every release - we'll be doing one soon.
