### ISSUE TITLE
Multipass Windows failing - possible AV issue

### ISSUE THREAD

**Issue by PirateBread** [CanonicalLtd/multipass#662]
Multipass service has been failing ever since our business deployed BitDefender AV.
I have added exceptions for the multipass directory, including all the DDLS and EXE's to no avail.

I have also raised this with BitDefender support.

> Faulting application name: multipassd.exe, version: 0.0.0.0, time stamp: 0x5c46c306
> Faulting module name: multipassd.exe, version: 0.0.0.0, time stamp: 0x5c46c306
> Exception code: 0xc0000005
> Fault offset: 0x00000000000af284
> Faulting process ID: 0x3960
> Faulting application start time: 0x01d4d34b89f3ef33
> Faulting application path: C:\Program Files\Multipass\bin\multipassd.exe
> Faulting module path: C:\Program Files\Multipass\bin\multipassd.exe
> Report ID: 8d87a1e3-70f1-4cb6-a9f1-c2b9d18bf557
> Faulting package full name: 
> Faulting package-relative application ID: 
>

**Comment by Saviq** [comment]
Hi @PirateBread did you get anywhere with this?

**Comment by Saviq** [comment]
Please report back if this still happens.
