### ISSUE TITLE
Disk image resized unnecessarily

### ISSUE THREAD

**Issue by Saviq** [CanonicalLtd/multipass#685]
When the user didn't pass a `--disk` option, we should not touch the image size.

**Comment by Saviq** [comment]
Actually I'm not sure any more... The default images are only 2GB big or so, and there's barely any space to work with... All the image formats are dynamic, meaning we don't actually allocate the size of the disk requested.

**Comment by ricab** [comment]
If the user does not specify anything, we want to strike a balance between 

1) more disk space, to reduce chance of failures from low disk, etc.
2) less disk space, to reduce waste (that the user is probably unaware of)

The default in the image has other sorts of goals, so I think it is reasonable that we come up with our own size. Of course the exact number is subjective. My feeling would be more on the 5G side.

**Comment by ricab** [comment]
For completeness, this seems to have been decided [here](https://github.com/CanonicalLtd/multipass/pull/149).

**Comment by Saviq** [comment]
Wow, that hurt! ;)

**Comment by ricab** [comment]
Oh, not my intention. And reconsidering is not a bad thing IMO. I forget decisions and their rationale all the time. And I can't remember what I committed last month, let alone a year ago :)
