### ISSUE TITLE
Connect doesn't default if only one instance available

### ISSUE THREAD

**Issue by popey** [CanonicalLtd/multipass#70]
`multipass connect` has a require parameter. I have just issues `multipass launch` so there is only one system running. Given multipass knows exactly how many systems are available, it would be super convenient that if the number of instances == 1 then chances are I wanted to connect to that one.

Perhaps `multipass launch` followed by `multipass connect` could do the right thing and just connect me to the recently launched system?

**Comment by Saviq** [comment]
We've discussed this and are generally in favour, only question is what to do when there are more than one instances and you issue `multipass connect` - do we interactively ask you which one to connect to, or error out?

**Comment by townsend2010** [comment]
Also, tab completion should fill out the only vm automatically, so ``multipass connect <tab><tab>`` should automatically fill that in.

**Comment by pekof** [comment]
`multipass connect` is now `multipass shell`.
I needed to look in code to realize that.
> We've discussed this and are generally in favour, only question is what to do when there are more than one instances and you issue `multipass connect` - do we interactively ask you which one to connect to, or error out?

Is this enhancement still desired?
Changing behavior `multipass connect` if only one, none or more than one instance is running could be confusing.
Should similar behavior be implemented for other commands e.g. `multipass stop` ?

If it's still desired feature I think that in case there are more instances running command should list running instances.

> Also, tab completion should fill out the only vm automatically, so `multipass connect <tab><tab>` should automatically fill that in.

That's interesting solution without changing behavior of `multipass shell` command.

**Comment by Saviq** [comment]
Yeah I'm gonna close this now. We're working to design a related solution, will keep you posted.
