### ISSUE TITLE
hitting ^C during multipass launch on Windows host has locked up other multipass commands

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#707]
Running multipass launch on a Windows 10 host and interrupting it has locked up further multipass commands, such as multipass list and multipass delete -all.  These subsequent commands just wait indefinitely and seem to be stuck.

**Comment by ricab** [comment]
Thank you for reporting. This is (at least partly) a consequence of sequential handling of multipass commands &ndash; a fallback approach currently in place to deal with concurrency issues. A long-term solution is being worked on but, ATM, no operation will be handled until the previous ones are finished. 
So if a ctrl+c fails to fully abort the ongoing operation, the following operations get blocked. 

The command might time out after a while (e.g. 5min for launch commands). If it doesn't can you try to restart the multipass daemon?

**Comment by ColinIanKing** [comment]
I'm a newbie to Windows, how does one restart the multipass daemon on Windows?

**Comment by ricab** [comment]
I am not very familiar with it either and I don't have access to it ATM. Do you have Powershell? If so `restart-service *multipass*` should do it: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-service?view=powershell-6

**Comment by ricab** [comment]
I am not very familiar with it either and I don't have access to it ATM. Do you have Powershell? If so `restart-service *multipass*` should do it: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-service?view=powershell-6

**Comment by ColinIanKing** [comment]
OK thanks, last time it happened I just rebooted the Windows box :-/

**Comment by ColinIanKing** [comment]
Not sure this is really closed at it still is an issue than can bite users.

**Comment by ricab** [comment]
Well it is a consequence of the sequential command handling that we are aware of and covered by #643.  But do let us know if you have further problems.

**Comment by gopiviavi** [comment]
The same issue happened and restart of service did not work.
restart using windows services - windows threw an error "could not stop the service" (name of the service is "multipass service")

**Comment by ricab** [comment]
Hi @gopiviavi, a lot has changed since this issue was reported. You're probably experiencing a similar symptom caused by a different problem. Would you be able to [report a new issue](https://github.com/canonical/multipass/issues/new?assignees=&labels=bug&template=bug_report.md&title=), including logs and other details there? Thank you.
