### ISSUE TITLE
boot time is slow because of loading of psmouse - this is probably redundant

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#710]
The psmouse probing takes several seconds during boot and it probably is redundant because cloud images in multipass don't really require psmouse support.

This can be avoided by simply blacklisting the psmouse by adding the following line to /etc/modprobe.d/blacklist.conf:

blacklist psmouse

and running:
sudo update-initramfs -k all -c

For example, on bionic:

Before:

[    2.204445] hv_utils: VSS IC version 5.0
[    2.416141] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
[    7.056088] psmouse serio1: trackpoint: IBM TrackPoint firmware: 0x01, buttons: 3/3
[    7.057905] input: TPPS/2 IBM TrackPoint as /devices/platform/i8042/serio1/input/input3
[    7.058739] input: AT Translated Set 2 keyboard as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/d34b2567-b9b6-42b9-8778-0a4ec0b955bf/serio2/input/input5

After (no psmouse probing etc):

[    2.230103] hv_utils: VSS IC version 5.0
[    2.234684] sd 2:0:0:0: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    2.242792] sd 2:0:0:0: [sda] Write Protect is off

..thus saving around around 4.5 seconds.

**Comment by ricab** [comment]
Thank you, this will be considered.

**Comment by townsend2010** [comment]
I'm not sure if this has been passed on to the cloud-image folks as they are the ones responsible for how the images are created.  As such, this isn't a Multipass issue per se, but an issue can be filed at https://bugs.launchpad.net/cloud-images/+bugs.

Thanks!
