### ISSUE TITLE
multipass on Windows - only has Xenial and Bionic cloud image support

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#711]
Multipass on Linux allows me to test Cosmic and Disco daily images, however the Windows variant only allows support of Xenial and Bionic.  Can newer releases of cloud images be supported too?

**Comment by townsend2010** [comment]
@ColinIanKing,

Hi, please join #multipass on the Canonical IRC for instructions on how to enable non LTS releases.
