### ISSUE TITLE
multipass on Windows 10 Pro with cloud images is slow to boot due to delays in console setup in initramfs

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#715]
Booting an azure kernel Cosmic cloud image with multipass on Windows 10 pro takes a long time. Using  systemd-analyze 25 seconds in kernel boot time is reported.  Digging into this, the kernel boot time is actually ~5 seconds, the other 20 seconds before systemd init is exec'd is actually in the initramfs.  I've instrumented the kernel to record the exec and exit times of each process in the kernel and the top offending processes in initramfs during boot are:

Duration    PID  process name
14.86832 262 /scripts/init-top/console_setup
2.48749 263 /bin/setfont
2.45357 268 /bin/setfont 
2.44657 291 /bin/setfont
2.44392 286 /bin/setfont
2.43545 279 /bin/setfont 
2.43161 274 /bin/setfont 
1.19233 255 /scripts/init-top/framebuffer

console_setup is calling setfont 7 times and each time setfint is taking more than 2.4 seconds to complete.  Also the framebuffer program is taking over a second to run.  

I'll now run this analysis on xenial, bionic, cosmic with generic and cosmic kernels to see if this is the same kind of issue across releases.

**Comment by ColinIanKing** [comment]
For Disco with azure kernel:

14.19028 275 console_setup
2.39020 276 setfont
2.34020 281 setfont
2.32915 293 setfont
2.32389 289 setfont
2.32319 285 setfont
2.32178 297 setfont
1.11417 268 framebuffer

**Comment by townsend2010** [comment]
Hi @ColinIanKing,

I'm pretty certain this isn't a Multipass issue in that we have no control how the console is set up in the cloud image.  However, I'm not really sure which project to report this under.  Perhaps https://bugs.launchpad.net/cloud-images is the proper place?  Or it may be a Hyper-V/Azure kernel interaction?

One way to totally remove Multipass from the equation is to create the VM in the `Hyper-V Manager` directly and use it to control the VM to see if you get the same result.

**Comment by ColinIanKing** [comment]
I'm not entirely sure where to place this bug report either.  I'm concerned that it's a font/framebuffer issue that occurs because it's not supported on the hypervisor that only occurs in a Windows hosted environment. I'll file the bug with the cloud images project. Apologies for any noise.

**Comment by townsend2010** [comment]
No worries at all.  We all have the same goal, but I just want to make sure the right set of eyes see the issue:)  I'll close this, but don't hesitate to enter any bugs like this and we can try to work out who is responsible.

**Comment by ColinIanKing** [comment]
For reference: https://bugs.launchpad.net/cloud-images/+bug/1823327
