### ISSUE TITLE
Instances Will Not Start

### ISSUE THREAD

**Issue by rayj00** [CanonicalLtd/multipass#721]
Just started to look into multipass.  I am getting the following error:

C:\Users\rayj0>multipass launch
launch failed: timed out waiting for instance to respond

C:\Users\rayj0>multipass list
Name                    State             IPv4             Release
preferred-curassow      STOPPED           --               Ubuntu 18.04 LTS
relieved-kudu           STOPPED           --               Ubuntu 18.04 LTS

C:\Users\rayj0>multipass start preferred-curassow
start failed: timed out waiting for instance to respond

I read about possible firewall issues so I turn off Norton 360 firewall but no help.

Any ideas?

Ray

**Comment by Saviq** [comment]
Hey @rayj00, can you `ping preferred-curassow.mshome.net`? That's how we find the IP of the instances. Now you're in the Hyper-V group, can you try launching another instance and see if that works? You could also try a reinstall, purging the data when asked, and also remove the instances in the Hyper-V manager.

**Comment by rayj00** [comment]
> 
> 
> Hey @rayj00, can you `ping preferred-curassow.mshome.net`? That's how we find the IP of the instances. Now you're in the Hyper-V group, can you try launching another instance and see if that works? You could also try a reinstall, purging the data when asked, and also remove the instances in the Hyper-V manager.
C:\Users\rayj0>multipass list
Name                    State                   IPv4                      Release
rayj                        RUNNING           UNKNOWN          Ubuntu 18.04 LTS
rayj2                      STOPPED             --                        Ubuntu 18.04 LTS
rayj3                      RUNNING           UNKNOWN          Ubuntu 16.04 LTS
rayj4                      STOPPED           --                          Ubuntu 16.04 LTS

C:\Users\rayj0>ping rayj/mshome.net
Ping request could not find host rayj/mshome.net. Please check the name and try again.

C:\Users\rayj0>ping rayj3/mshome.net
Ping request could not find host rayj3/mshome.net. Please check the name and try again.

C:\Users\rayj0>multipass launch
launch failed: timed out waiting for instance to respond

C:\Users\rayj0>multipass list
Name                    State             IPv4             Release
rayj                    RUNNING           UNKNOWN          Ubuntu 18.04 LTS
rayj3                   RUNNING           UNKNOWN          Ubuntu 16.04 LTS
noted-guineapig         RUNNING           UNKNOWN          Ubuntu 18.04 LTS
rayj4                   DELETED           --               Not Available
rayj2                   DELETED           --               Not Available

C:\Users\rayj0>ping noted-guineapig
Ping request could not find host noted-guineapig. Please check the name and try again.

And as with multipass,  I know nothing about Hyper-V?

Ray

**Comment by Saviq** [comment]
It's '.mshome.net', not '/mshome.net'. Hyper-V is the native Microsoft virtualization platform (you can find "Hyper-V Manager" in your apps) that Multipass uses behind the scenes. It looks like the _Default Switch_ that's used for networking for the instances is not working. Can you check it exists in the Hyper-V Manager? And that the instances have it selected as the network they're connected to?

**Comment by rayj00** [comment]
> Hey @rayj00, can you `ping preferred-curassow.mshome.net`? That's how we find the IP of the instances. Now you're in the Hyper-V group, can you try launching another instance and see if that works? You could also try a reinstall, purging the data when asked, and also remove the instances in the Hyper-V manager.

So   after the uninstall and re-install  of multipass, I have new instances that are in the STATE of RUNNING, but with UNKNOWN IPv4.

**Comment by rayj00** [comment]
> 
> 
> It's '.mshome.net', not '/mshome.net'. Hyper-V is the native Microsoft virtualization platform (you can find "Hyper-V Manager" in your apps) that Multipass uses behind the scenes. It looks like the _Default Switch_ that's used for networking for the instances is not working. Can you check it exists in the Hyper-V Manager? And that the instances have it selected as the network they're connected to?

Not sure what I should be looking for but here is what I got:
![image](https://user-images.githubusercontent.com/6609523/56226606-91fe1780-6041-11e9-90b6-d7da8174c2a8.png)

**Comment by Saviq** [comment]
Outside of there, in settings for a particular instance, can you see them being connected to that default switch?

**Comment by rayj00** [comment]
> 
> 
> Outside of there, in settings for a particular instance, can you see them being connected to that default switch?
![image](https://user-images.githubusercontent.com/6609523/56228852-9f69d080-6046-11e9-8557-033af3bfe5a0.png)

**Comment by rayj00** [comment]
Nice catch with the /mshome.net   I changed to rayj.mshome.net but no change.

**Comment by Saviq** [comment]
All of this looks sane, it's as if the Default Switch (it's provided by Windows) is not working properly :/

This is clutching by straws now, but do you have all of the Windows updates installed?

**Comment by rayj00** [comment]
> 
> 
> All of this looks sane, it's as if the Default Switch (it's provided by Windows) is not working properly :/
> 
> This is clutching by straws now, but do you have all of the Windows updates installed?

![image](https://user-images.githubusercontent.com/6609523/56233526-3fc4f280-6051-11e9-9d7f-c5ca454a168e.png)

**Comment by rayj00** [comment]
Can someone post all of the correct settings in Hyper-V?

Thanks,

Ray

**Comment by rayj00** [comment]
Created a VM with Hyper-V. Default is Ubuntu 18.04.1 LTS Desktop.  I could access it but there is no network connectivity.  This is on a laptop with WiFi connection.  So appears multipass is not nearly ready for prime time, correct?

**Comment by Saviq** [comment]
@rayj00 Hyper-V is an internal Windows hypervisor. That there isn't networking in the VM after you created it with Hyper-V itself means that it's a Hyper-V/Windows issue, not Multipass. The Default Switch should be set up by Windows, and that's what does not seem to happen for you. You're the first one to encounter this with Multipass that we know of, sorry that you're not having luck…

Try searching for "Hyper-V Default Switch no network", there seem to be some threads about this, maybe they will guide you to a fix.

**Comment by Saviq** [comment]
I'm going to close this as it's not a Multipass issue, but please report back if you manage to fix it.
