### ISSUE TITLE
MacOS hyperkit: [ERROR] Found a reference to cluster outside the file

### ISSUE THREAD

**Issue by joedborg** [CanonicalLtd/multipass#722]
On MacOS 10.14.4 and Multipass 0.6.0.  Possibly related to https://github.com/CanonicalLtd/multipass/issues/595.

```bash
multipass launch --name banana --mem 2G --disk 40G bionic
Starting banana /[2019-04-15T16:17:18.803] [error] [banana] hyperkit: [ERROR] Found a reference to cluster 38621743694936 outside the file (max cluster 15543) from cluster 13452.512

[2019-04-15T16:17:18.803] [error] [banana] hyperkit: [ERROR] Mirage block device raised exception: Qcow.Make(Base)(Time).Reference_outside_file(_, _)

[2019-04-15T16:17:18.803] [error] [banana] Mirage-block error: Block device is disconnected

[2019-04-15T16:17:18.803] [error] [banana] Could not open mirage-block device: Invalid argument
```

However, I have tried the cleanup seen in https://github.com/CanonicalLtd/multipass/issues/595, but the issue persists.

**Comment by Saviq** [comment]
Hey @joedborg did you ensure `/var/root/Library/Caches/multipassd` is gone after uninstall?

Also, does `xenial` launch with these same settings?

**Comment by joedborg** [comment]
Hi @Saviq, I tried that a few times again, but ended up having to remove the enitre a of `multipass` and install again.  I generate and destroy a few containers a day and it seems to trigger this error now and then.

**Comment by Saviq** [comment]
Hi @joedborg did you see this again recently? Please reopen if so.
