### ISSUE TITLE
Only ubuntu images are supported?

### ISSUE THREAD

**Issue by lhorace** [CanonicalLtd/multipass#737]
Hello,

My impression is that `multipass` supports only Ubuntu images?

Cheers

**Comment by Saviq** [comment]
Using the snap, on Linux you can pass arbitrary URLs to `launch`, provided the images are in a format qemu can consume and the image has `cloud-init`. We've successfully launched Fedora and Debian cloud images.

We're considering how to integrate that into the tool, but Ubuntu will remain the focus.

**Comment by Saviq** [comment]
I'll close this issue, please reopen if you think this is not exhausted.

**Comment by tekumara** [comment]
On macOS it appears only built-in Ubuntu images are supported, and not arbitrary images:
```
$ multipass launch -n fed https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz
launch failed: http and file based images are not supported
```

**Comment by HLFH** [comment]
Duplicate of https://github.com/canonical/multipass/issues/1260.

**Comment by h3ct0rjs** [comment]
Hi @HLFH Do you know if is it possible to run another binary image like fedora? 

Regards, 
H

**Comment by atomlab** [comment]
Hello! Where do I need to place the downloaded Debian Cloud image to run it on MacOS with M1 processor?
https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-genericcloud-arm64-daily.qcow2
