### ISSUE TITLE
Initial cloud image is painfully slow to download

### ISSUE THREAD

**Issue by popey** [CanonicalLtd/multipass#751]
I'm running a snapcraft workshop at a college in the USA. The systems have not had snapcraft or multipass installed before. I just installed both and tried `snapcraft init` & `snapcraft`. It's been some minutes now and the image hasn't finished downloading. The bandwidth here isn't an issue...

![Screenshot from 2019-04-28 10-45-25](https://user-images.githubusercontent.com/1841272/56868096-c3140b80-69a2-11e9-878e-ad881cbf154c.png)

15 mins in and we're 29% done on one machine. 

What can I do to debug or otherwise find out what's going on. Having a long lag just to get the initial image is quite painful.

**Comment by Saviq** [comment]
Hi @popey, have you tried downloading directly from http://cloud-images.ubuntu.com/ ? Unfortunately, AFAIK it's not backed by any CDN, so if the server gets really busy, the download times are like that…

Unless obviously you can confirm that it's Multipass itself downloading slow, while the servers are responding fast, we'd have to look into that then.

**Comment by pcgeek86** [comment]
I'm seeing slow image downloads, too.

* MacOS 10.14.5
* multipass 0.7.0

Using Activity Monitor on MacOS, I can see a download rate of a couple hundred kilobytes per second.

<img width="553" alt="Screen Shot 2019-06-05 at 9 51 37 AM" src="https://user-images.githubusercontent.com/466713/58974626-a627e080-8777-11e9-8549-70b25f1d9326.png">

If I were to download the images separately, where should I place them on the filesystem?

**Comment by Saviq** [comment]
@pcgeek86 can you confirm the download is faster when downloading separately?

I'm afraid it's currently not possible on macOS to "inject" images into Multipass. But unless it is to blame for the slow downloads, that shouldn't matter. Remember it caches the image so you'll only have to download it once when the image is updated.

**Comment by townsend2010** [comment]
Yeah, the downloading of cloud-images is slow today.  Nothing Multipass can do about that.

**Comment by pcgeek86** [comment]
Yeah, it's slow with the direct links as well @Saviq. Oh well, not a huge deal, but whoever hosts these images might want to find a different place to host them! Thanks!

**Comment by popey** [comment]
"Remember it caches the image so you'll only have to download it once when the image is updated."

No good if (like me) you're doing a class of 20 machines. That's 20 people all trying to download and getting terrible speeds. It can adversely affect the ability to run a workshop. This speed problem would make me seriously consider using multipass for any future workshops, as this step is so unpredictable. 

For the situation I had, we kicked everyone out of the room and spent an hour pre-downloading the images on all the systems.

**Comment by townsend2010** [comment]
@popey,

Have you reached out to the cloud image folks and told them about this?  It's really on their end that this is the problem.  Multipass can only download the image as fast as it's given.

**Comment by pcgeek86** [comment]
Also just wanted to point out that you can override the image location @popey. You can use a local file or a custom `https` URL. Maybe consider keeping a copy of the latest cloud image on an Amazon S3 Bucket or similar cloud storage service. Not the ideal fix, but at least you could still get the benefits of multipass in your classroom setups.

```
Usage: multipass launch [options] [[<remote:>]<image> | <url>]
Create and start a new instance.

Options:
  -h, --help           Display this help
  -v, --verbose        Increase logging verbosity, repeat up to three times for
                       more detail
  -c, --cpus <cpus>    Number of CPUs to allocate
  -d, --disk <disk>    Disk space to allocate. Positive integers, in bytes, or
                       with K, M, G suffix. Minimum: 512M.
  -m, --mem <mem>      Amount of memory to allocate. Positive integers, in
                       bytes, or with K, M, G suffix. Mimimum: 128M.
  -n, --name <name>    Name for the instance
  --cloud-init <file>  Path to a user-data cloud-init configuration, or '-' for
                       stdin

Arguments:
  image                Optional image to launch. If omitted, then the default
                       Ubuntu LTS will be used.
                       <remote> can be either ‘release’ or ‘daily‘. If <remote>
                       is omitted, ‘release’ will be used.
                       <image> can be a partial image hash or an Ubuntu release
                       version, codename or alias.
                       <url> is a custom image URL that is in http://, https://,
                       or file:// format.
```

**Comment by Saviq** [comment]
@popey you could have also used a caching proxy, Multipass respects the standard `http(s)_proxy` environment variables.

There's also `snap set proxy.http(s)` to get that into the instances. That is unfortunately not documented.

Care to propose a topic, or even better - submit one - to [our documentation](https://community.ubuntu.com/t/multipass-documentation-outline/8294)?

**Comment by Saviq** [comment]
I'm going to close this as it's not a Multipass issue.

**Comment by dimaqq** [comment]
I'd like to chime in that it's still kinda slow.

Granted, it's not a multipass coding issue, yet something could be improved in the overall service architecture. Initial devex is super important.

P.S. I'd like to test this out in a couple of networking environments, what's the easy way to drop download cache?

**Comment by townsend2010** [comment]
Hi @dimaqq!

Which platform are you using, ie, macOS, Windows, or Linux?

**Comment by dimaqq** [comment]
MacOS host, M2, so aarch64, `multipass launch` command, thus default image.

I've retried this in a known good network environment, and the result is not too bad.
Could be better, speedof.me shows 5x max download speed, but also not terrible, 10~13 MB/s.

![Screenshot 2023-10-26 at 16 18 18](https://github.com/canonical/multipass/assets/662249/c316d2ec-ade5-44d9-ad0f-d23c169dd670)

It's kinda good enough for me, though if you track download speeds from around the world?
