### ISSUE TITLE
Multipass on Windows 10 Pro, cannot connect to multipass socket

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#768]
Clean install of Multipass 6.1 on Windows Pro, and I'm seeing the following launch problems:

multipass launch -c 1 -d 4G -m 1G -n bionic-test bionic
launch failed: cannot connect to the multipass socket
Please ensure multipassd is running and 'localhost:50051' is accessible

I've tried rebooting and removing/reinstalling Multipass 6.1 on Windows Pro but I get the same issue. Any ideas?

**Comment by townsend2010** [comment]
Hey @ColinIanKing,

So this indicates that `multipassd` is not running.  Unfortunately, I think you are being bitten by #573 (a stupid Hyper-V issue) and the only workaround I've found is doing what I wrote in https://github.com/CanonicalLtd/multipass/issues/573#issuecomment-460359962.  Hopefully that will work for you.

**Comment by ColinIanKing** [comment]
Yep, disabling/rebooting/renabling/rebooting Hyper-V helped to resolve this issue. Thanks.
