### ISSUE TITLE
In the snap store, the license is "proprietary"

### ISSUE THREAD

**Issue by xordspar0** [CanonicalLtd/multipass#777]
It looks like the license for this code is GPLv3. Shouldn't the snap store page reflect that?

**Comment by Saviq** [comment]
Thanks for pointing that out, we'll be fleshing out our snap store page soon :)

**Comment by kubajecminek** [comment]
Currently it shows **GPL-3.0 OR Proprietary** on the [Snapcraft](https://snapcraft.io/multipass) website. If that's intentional, can you please explain what does that mean?

**Comment by ricab** [comment]
Hi @kubajecminek, the Linux version of Multipass is GPL-3.0, including the snap. However, the Windows and macOS versions include proprietary code too, so they have a proprietary license.
