### ISSUE TITLE
`exec` hangs under snapcraft and electron-builder

### ISSUE THREAD

**Issue by Saviq** [CanonicalLtd/multipass#847]
0.7.1 is still affected.
snapcraft 3.3 (as no latest version for macOS).

```
Starting snapcraft 3.3 from /usr/local/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/snapcraft/cli.
Parts dir /Volumes/ramdisk/electron-builder-test/dist/__snap-x64/parts
Stage dir /Volumes/ramdisk/electron-builder-test/dist/__snap-x64/stage
Prime dir /Volumes/ramdisk/electron-builder-test/dist/__snap-x64/prime
Setting target machine to 'amd64'
Using 'snap/snapcraft.yaml': Project assets will be searched for from the 'snap' directory.
Launching a VM.
Running multipass start snapcraft-se-wo-template

                                                                                
Starting snapcraft-se-wo-template  / 
                                                                                

                                                                                
snapcraft is running as a snap False, SNAP_NAME set to ''
Holding refreshes for snaps.
Running multipass exec snapcraft-se-wo-template -- sudo -i env SNAPCRAFT_HAS_TTY=False snap set core refresh.hold=2019-06-19T12:22:12.309738Z
```

and that's all. 

Works from terminal, but hangs if run as part of test runner (electron-builder uses Jest).
What I can do? Is there any env that I can set to disable any detection/etc?

_Originally posted by @develar in https://github.com/CanonicalLtd/multipass/issues/678#issuecomment-503497989_

**Comment by Saviq** [comment]
@develar can you please point to a `snapcraft.yaml` we could use to try and reproduce? Thanks!

**Comment by develar** [comment]
Hangs on macOS even without Jest, but just as a regular electron builder invocation. It is not really critical, because electron-builder uses `snapcraft` only if custom stage packages are specified. Still, quite important problem.

> can you please point to a snapcraft.yaml we could use to try and reproduce? Thanks!

I prepared for you small example without NodeJS/electron-builder.


Unpack [dist.zip](https://drive.google.com/uc?export=download&id=1Vig8jF_t3dXxlNvezsDZYOBilItTtXSK) and `cd dist`.
Execute
```
SNAPCRAFT_ENABLE_DEVELOPER_DEBUG=yes ./app-builder-bin/mac/app-builder snap --app linux-unpacked --stage __snap-x64 --arch amd64 --output se-wo-template_1.1.0_amd64.snap --executable se-wo-template --extraAppArgs=--no-sandbox
```
In the archive also `app-builder` executable for Linux, but I didn't check — does it hang only on macOS or Linux is also affected.

**Comment by develar** [comment]
Relevant lines in my code: 

1) https://github.com/develar/app-builder/blob/1392c772bdb5cd10d33cdc61de83197537a0fbc3/pkg/package-format/snap/snap.go#L332
2) https://github.com/develar/app-builder/blob/1392c772bdb5cd10d33cdc61de83197537a0fbc3/pkg/util/exec.go#L11

Please note, that I tried several variants — buffer stderr/stdout to byte array, redirect to file. Doesn't change situation (`SNAPCRAFT_HAS_TTY` true/false doesn't matter).

**Comment by develar** [comment]
Hi, any news?

**Comment by Saviq** [comment]
Hi @develar, sorry, we were focused on other things, we'll get to your issue ASAP, but there's a chance #772 is another instance of the same underlying issue.

**Comment by townsend2010** [comment]
I'm quite sure this is the same underlying bug as #772.  I'm going to close this bug and we'll that other bug to track the issue.
