### ISSUE TITLE
[macos] When stopping instance try 'shutdown -h now' first

### ISSUE THREAD

**Issue by townsend2010** [CanonicalLtd/multipass#869]
On irc, @hatched ran into a scenario where he had the microk8s snap installed in an instance and when he tried to stop the instance, he'd see the following error:
`Stopping work /[2019-06-27T13:11:52.001] [error] [work] process error occurred Crashed`
which indicates that the `hyperkit` process is not cleanly terminating within 15 seconds and then gets whacked.

However, upon debugging the issue, if he issued a `shutdown -h now` directly in the instance, it shut down very quickly.  So there seems to be a difference between the current `QProcess::terminate()` way of shutting down the instance and explicitly issuing a shutdown in the instance.

I propose `multipass` first tries to inject a `shutdown` in the instance.  If that is not possible, then the fallback is the current way of shutting down an instance.

**Comment by Saviq** [comment]
I thought that `SIGINT` was meant to be interpreted as ACPI shutdown by hyperkit, @gerboland do you know if that's not the case?

**Comment by gerboland** [comment]
@Saviq comments in my code say that`SIGTERM` to hyperkit should trigger ACPI shutdown. I'd need to re-dig to check that

**Comment by gerboland** [comment]
Yep hyperkit code confirms that. Either something disables the ACPI shutdown thingy in the VM, or something else breaks it..

**Comment by gerboland** [comment]
I'd really like to be able to reproduce this issue before trying a `shutdown -h now` as I've no idea if that will actually solve the issue. I've installed microk8s and enabled a bunch of services, but the VM still responds to shutdown requests just fine. Only if I explicitly disable ACPI handling (by hacking kernel command line, not something user can do) can I do break the current approach.

I'll liaise with hatch on IRC about it

**Comment by Saviq** [comment]
Let's fix this by #870.
