### ISSUE TITLE
Allow backends prefer a different image type

### ISSUE THREAD

**Issue by Saviq** [CanonicalLtd/multipass#872]
We now received images with the `linux-kvm` kernel that should boot much faster on our `qemu` and `libvirt` backends. They unfortunately have no way to select those images, we globally default to `disk1.img` images.

Because not all image types may be available for a given image, backends should be able to prefer another type (`disk-kvm.img` for `qemu`/`libvirt`, maybe another optimized for other backends).

Backends need to then know what image got downloaded (they should not be selecting / downloading themselves) so they can prepare it appropriately.

**Comment by townsend2010** [comment]
Looks like a dup of #625 :smiley:
