### ISSUE TITLE
failed to start qemu instance

### ISSUE THREAD

**Issue by aalhaji** [CanonicalLtd/multipass#925]
Hello,

I tried to run 'snapcraft' on Raspbian but I encountered the error:
```
Launching a VM.
launch failed: failed to start qemu instance                                    
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```
so I tried running 'multipass launch' which led to the same error. I saw on a different thread that this might be a firewall issue, so I disable iptables, didn't help. So I removed iptables completely - still doesn't work. I ran multipass launch snapcraft:core18 -vvv and I received the same 'launch failed: failed to start qemu instance'. Could someone help me with this problem?

**Comment by Saviq** [comment]
Hi @aalhaji can you run `kvm-ok` (from the `cpu-checker` package) please?

When running with `-vvv`, was the failure the only message you got?

**Comment by aalhaji** [comment]
> Hi @aalhaji can you run `kvm-ok` (from the `cpu-checker` package) please?
> 
> When running with `-vvv`, was the failure the only message you got?

Hi Saviq! Yes, the failure message is the only thing I got from -vvv. I'm on a Raspberry Pi (Raspbian), so I'm afraid it's been a struggle to get kvm from what I've read online. I think it's best I find other ways to take my app to production.

**Comment by Saviq** [comment]
@aalhaji if you get to a state where you can use qemu/kvm, but Multipass is not working, please let us know.
