### ISSUE TITLE
DNS Not Configured - VM is unusable 

### ISSUE THREAD

**Issue by rajasoun** [CanonicalLtd/multipass#933]
Steps:
1. multipass launch -n vm
2. multipass shell vm 
---
0 packages can be updated.
0 updates are security updates.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. 
Check your Internet connection or proxy settings
---
3. cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0

So nameserver is not configured properly

---------------------------- 

Environment:
macOS Mojave - 10.14.6

multipass  0.8.0+mac
multipassd 0.8.0+mac

**Comment by Saviq** [comment]
Hi @rajasoun, why do you say nameserver is not configured properly? `127.0.0.53` is the loopback address on which `systemd-resolved` listens by default.

You can check what upstream DNS it's looking at by issuing `systemd-resolve --status` inside the instance.

Are you running any firewall software? macOS has a built in one that might need to be disabled for Multipass to function correctly. Also things like Little Snitch can pose problems.

**Comment by rajasoun** [comment]
The instance is not able to connect to the Internet
If I add the following line in /etc/resolv.conf manually 
nameserver 8.8.8.8
nameserver 8.8.4.4 

Its able to conect

**Comment by gerboland** [comment]
Could you please share the output of this command:

    sudo lsof -iTCP:53 -iUDP:53 -n -P

For some reason the local DNS server, mDNSResponder is not working to provide DNS services to the VM. The above command will show if it is bound to port 53 as expected, or if something else is (dnscrypt-proxy can cause this)

**Comment by BretFisher** [comment]
@gerboland I use `dnscrypt-proxy`, is there a recommended workaround other than manual `resolv.conf` editing?

**Comment by Saviq** [comment]
@BretFisher you can use [`multipass launch --cloud-init…`](https://discourse.ubuntu.com/t/multipass-launch-command/10846), passing the [appropriate cloud-init directives](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#configure-an-instances-resolv-conf).

**Comment by Saviq** [comment]
Please open another issue if you can't get this to work.

Multipass won't be able to detect all the host network configuration managed by third party apps / firewalls.

**Comment by nmofonseca** [comment]
Hello, Was there any solution for this? using --cloud-init  doesn't seem to work, the resolv conf module according to the documentation doesn't support Ubuntu/Debian:
https://cloudinit.readthedocs.io/en/latest/topics/modules.html#resolv-conf 
I am not finding an easy way to do this on the launch only manually after the instances are runing.
