### ISSUE TITLE
Multipass VM seems to timeout and needs uninstall/install to recover.

### ISSUE THREAD

**Issue by vitimiti** [CanonicalLtd/multipass#934]
Using Ubuntu 19.10 and multipass 0.8.0.

From time to time, when I am building and rebuilding a snap package when testing, it will eventually simply fail, sending the error

An error occurred when using 'multipass' to query the status of the instance: returned exit code 2: info failed: failed to obtain exit status for remote process 'free -b | sed '1d;3d' | awk '{printf $3}'': timeout

Uninstalling multipass and reinstalling appears to be the easiest solution that I've found for now.

uname -a message: Linux vmatia-MS-7978 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

snap --version: 
snap    2.39.3
snapd   2.39.3
series  16
ubuntu  19.04
kernel  5.0.0-20-generic

snapcraft --version:
snapcraft, version 3.6

**Comment by townsend2010** [comment]
Hi @vitimiti,

We have a short timeout when running commands via `ssh` in the instance and if the instance has high CPU usage or is low on memory, the command can timeout.

Does the issue keep occurring if you manually run `multipass info $name_of_instance`?  Does the instance react to manually stopping via `multipass stop $name_of_instance`?

**Comment by Saviq** [comment]
Please let us know if this is still a problem.
