### ISSUE TITLE
Launching instances using shortcuts detailed in `multipass find` output

### ISSUE THREAD

**Issue by philroche** [CanonicalLtd/multipass#94]
Firstly, thank you for this tool :)

I wanted to launch a bionic instance so I used `multipass find` to find the images available and was shown the following for bionic:

```
multipass launch …   Starts an instance of   Image version
----------------------------------------------------------
daily:18.04          Ubuntu 18.04 LTS        20180124
   (or: b, bionic, devel)
```

From this I assumed that I could try `multipass launch --name bionic b` or `multipass launch --name bionic bionic` or `multipass launch --name bionic devel` but this proved not to be the case. `multipass launch --name bionic daily:18.04` did work as expected.

```
$ multipass launch --name bionic b
failed to launch: Too many images matching "b"          

$ multipass launch --name bionic bionic
failed to launch: Unable to find an image matching "bionic"

$ multipass launch --name bionicdevel devel
failed to launch: Unable to find an image matching "devel"  
```
Is this a bug or have I misunderstood the output of `multipass find`?

**Comment by philroche** [comment]
This might be a duplicate of https://github.com/CanonicalLtd/multipass/issues/8

**Comment by townsend2010** [comment]
Hi!  Thanks for taking the time to enter this bug.

So, yeah, the find command is not very intuitive:)  But if you use:

``$ multipass launch daily:bionic``

(without the ``--name``) that will do what you want.  ``--name`` is for actually naming the instance what you want to call it and not use a generated name.  See ``multipass launch --help`` for more info.

**Comment by philroche** [comment]
Yes sorry it was a little confusing leaving `--name bionic` in my examples. 

Does this mean that the sortcuts "bionic", "b" or "devel" are not valid and should read "daily:bionic", "daily:b" or "daily:devel"?

**Comment by townsend2010** [comment]
Oh, I see, you were actually naming the instance ``bionic``:)

Yes, it needs to have ``daily:``.  Like ``daily:18.04``, ``daily:bionic``, ``daily:b``, etc.  We tried putting ``daily:`` in front of all of the possible aliases listed there, but it didn't look right and seemed redundant.  But I guess we were wrong:)

Sorry for the confusion.

**Comment by philroche** [comment]
No worries. Thanks for the explanation. Feel free to close this issue.

**Comment by townsend2010** [comment]
@philroche Great thanks! We'll just track the ``find`` wording in #8.
