### ISSUE TITLE
Is there any known effort to create a multipass provider for Vagrant?

### ISSUE THREAD

**Issue by lestephane** [CanonicalLtd/multipass#952]
I'd like to get rid of Virtualbox at some point in favour of multipass,
but the Vagrant workflow is something I'm very much used to by now.

**Comment by Saviq** [comment]
Hi @lestephane can you describe a bit more how would you envision this working?

**Comment by lestephane** [comment]
I was just thinking that, in the same way we have an LXD and Virtualbox vagrant providers, we could have a multipass vagrant provider. This would allow more people to use it and give feedback.

Meanwhile I tried multipass through snapcraft and regularly had situations where a VM was stuck, and I had to switch to the LXD mode with snapcraft. So I'm no longer using multipass, and you can ignore my question.

**Comment by Mte90** [comment]
any updates from that side?

**Comment by Saviq** [comment]
@Mte90 if someone's using vagrant, there's very little Multipass can provide it… Vagrant already talks to the various backends we support, so not sure what the gain is here.

We're unlikely to work on that, but if someone has the spare time and need, great :)

**Comment by fredleger** [comment]
I guess the issue should be on Vagrant project instead of multipass. The way i'm seing it is that there is not much work to make it functional because multipass is clearly simplier than VB

**Comment by fredleger** [comment]
For the one landing here there i s a few you can try
1) https://github.com/Fred78290/vagrant-multipass
2) https://github.com/lukaszkorecki/drifter
3) Vagrantfile with no provider and doing provsionning through local exec
