### ISSUE TITLE
macOS - reboot - old multipass VMs behave strange with CLI

### ISSUE THREAD

**Issue by carmine** [CanonicalLtd/multipass#971]
I've launched many images. Most are stopped. My machine crashed and rebooted. When I try to start one of the VMs, I get the first error message below. I can launch new ones and enter them.

The strange behavior is that, if I exit the just launched VM, and try to start one of the older VMs, then the new VM enters the stopped state.

In this example, demo is an old VM, and mk8s is a new VM.

| => multipass shell demo
start failed: cannot connect to the multipass socket                            
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible
(base) ________________________________________________________________________________
| ~/dev/opensource/kubeflow/website @ aurelius (carmine) 
| => multipass shell mk8s
Starting mk8s  Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

**Comment by Saviq** [comment]
I think the problem here was that you were trying to communicate with Multipass too early after boot.
