### ISSUE TITLE
Could not generate a new UUID error

### ISSUE THREAD

**Issue by SayusiAndo** [CanonicalLtd/multipass#972]
Hi,

I randomly get this error message on Windows 10 Pro with VirtualBox driver. So far the only workaround is rebooting the host machine or rather reinstall multipass.

```
PS C:\Windows\system32> multipass launch ubuntu -n sdf2
launch failed: Could not generate a new UUID: Process failed to start: The system cannot find the file specified.
PS C:\Windows\system32>
```

Please, let me know what other info you need. Unfortunately, ```-vvv``` doesn't work with ```launch``` #962 

Second round with fresh multipass install and cleaned up registry:

```
PS C:\Windows\system32> multipass set local.driver=virtualbox
PS C:\Windows\system32> multipass get local.driver
virtualbox
PS C:\Windows\system32> multipass list
No instances found.
PS C:\Windows\system32> multipass launch ubuntu -n sdf
launch failed: Could not generate a new UUID: Process failed to start: The system cannot find the file specified.
PS C:\Windows\system32>
```

**Comment by townsend2010** [comment]
Hi @SayusiAndo!

So, VirtualBox is not finding the particular instance image and it's not clear why the image is not there.  This doesn't happen every time and only randomly, right?  Do you see any download occur before this happens?  What happens if you choose a different instance name after the first time this occurs like the following?
```
PS C:\Windows\system32> multipass launch ubuntu -n sdf
launch failed: Could not generate a new UUID: Process failed to start: The system cannot find the file specified.
PS C:\Windows\system32> multipass launch ubuntu -n foo
```

**Comment by SayusiAndo** [comment]
Once this occurs after that it happens always and doesn't matter whether I'm admin or not.

In this particular case download happened before. Later, I'll try out a few other scenarios too.

**Comment by SayusiAndo** [comment]
What I did:

**Scenario 1**:
- uninstall VirtualBox
- uninstall Multipass
- clean registry with CCleaner
- reboot the machine
- install VirtualBox to a custom directory
- install Multipass to a custom directory
- multipass launch ubuntu -n foo
- result: downloading and initializing and the error message above

**Scenario 2**:
- uninstall VirtualBox
- uninstall Multipass
- clean registry with CCleaner
- reboot the machine
- install VirtualBox - no custom directory
- install Multipass - no custom directory
- multipass launch ubuntu -n foo
- result: works like a charm

I haven't replayed Scenario multiple times in order to be absolutely sure custom directory messes up things, but one thing is sure, all the previous cases I have both VirtualBox and Multipass installed in custom directories.

**Comment by townsend2010** [comment]
@SayusiAndo,

Perhaps there is some bug in Multipass when it is installed in an alternate location.  We will need to look into that.

**Comment by townsend2010** [comment]
Hi @SayusiAndo,

After some investigation, I think I figured out the issue.  So if you install VirtualBox to a custom directory, Multipass cannot find the various VirtualBox binaries since VirtualBox does not modify the `PATH` environment variable.  We hard-coded Multipass to look in the default install directory, but we obviously cannot account for an alternate install location.

That said, you can edit the `PATH` environment variable that `multipassd` uses and add the custom VirtualBox install directory there and then it should work.

Let me know if this works for and if so, then we'll close this bug.

**Comment by Saviq** [comment]
As for installing VirtualBox in a different location, its installer actually sets a system environment variable, `ORACLE_…something`. I was planning to add that to Multipass's `PATH`.

And @townsend2010's work on "backend health checks" will greatly improve error handling - if it can't find VBoxManage, we will tell you that, instead of failing with a cryptic error.

**Comment by SayusiAndo** [comment]
I reinstalled VirtualBox to the place it recommends, everything is working fine since then.

**Comment by Saviq** [comment]
Great! I'll close this issue then.

**Comment by brutestack** [comment]
For those who don't want to reinstall VirtualBox to default location:
you can create symbolic link from default location to your real VirtualBox location.
In my case, I have VirtualBox installed on drive D, so creating symlink like this helped:

> mklink /d "C:\Program Files\Oracle" "D:\Program Files\Oracle"

Do this from command prompt as Administrator

**Comment by krlinus** [comment]
IMHO this is a clear bug or atleast qualifies as a feature request
I cannot install stuff on my c: as I have a limited nvm configuration, and upon which the OS happens to be installed. So, I install my stuff on D:. I assume my situation is common in these times. Additionally, if you can't customize the installation location then the application is not there yet

**Comment by krlinus** [comment]
> For those who don't want to reinstall VirtualBox to default location:
> you can create symbolic link from default location to your real VirtualBox location.
> In my case, I have VirtualBox installed on drive D, so creating symlink like this helped:
> 
> `mklink /d "C:\Program Files\Oracle" "D:\Program Files\Oracle"`
> 
> Do this from command prompt as Administrator

Thanks for this tip. I moved me a notch closer, however I ended up here:
D:\>multipass launch
One quick question before we launch … Would you like to help
the Multipass developers, by sending anonymous usage data?
This includes your operating system, which images you use,
the number of instances, their properties and how long you use them.
We’d also like to measure Multipass’s speed.

Send usage data (yes/no/Later)? no
launch failed: Could not start VM: Waiting for VM "thoughtful-chimaera" to power on...
VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

I am left in a deep mystery as to where actually it is working - on my C or D:. My C: simply has no space; so I have left a comment above.

**Comment by Saviq** [comment]
Hi @krlinus this is the important part:
```
VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
```

You need to enable virtualization in your BIOS settings. If that doesn't help, please file a new issue.

**Comment by krlinus** [comment]
> Hi @SayusiAndo,
> 
> After some investigation, I think I figured out the issue. So if you install VirtualBox to a custom directory, Multipass cannot find the various VirtualBox binaries since VirtualBox does not modify the `PATH` environment variable. We hard-coded Multipass to look in the default install directory, but we obviously cannot account for an alternate install location.
> 
> That said, you can edit the `PATH` environment variable that `multipassd` uses and add the custom VirtualBox install directory there and then it should work.
> 
> Let me know if this works for and if so, then we'll close this bug.

Here's how that goes for me:
D:\sunil\tools\virtualbox>set PATH=%PATH%;D:\apps\Oracle

D:\sunil\tools\virtualbox>multipass list
No instances found.

D:\sunil\tools\virtualbox>multipass launch
launch failed: Could not generate a new UUID: Process operation timed out

**Comment by Saviq** [comment]
@krlinus this may very well be a different issue, please try with `multipass launch -vvv` and / or look [in the Event Viewer](https://multipass.run/docs/accessing-logs) - and file a new issue please.

**Comment by sun603** [comment]
It is possible to set the path to virtualbox for just multipass in some configuration file,  like "~/.multipassrc"?
I am new to multipass. I am not sure if that's possible.

**Comment by Saviq** [comment]
Hi @sun603 not currently, we'll be reading the VirtualBox location from the registry, soon, though.

**Comment by tarkhil** [comment]
I've installed VirtualBox and multipass right now in default places.

VBoxManage.exe: error: UUID {530b2467-38e3-4af1-976a-4951b9f23301} of the medium 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\ubuntu-lts\ubuntu-18.04-server-cloudimg-amd64.vdi' does not match the value {fe8cbd06-580c-4928-9e9b-f19eeae683e0} stored in the media registry ('C:\WINDOWS\system32\config\systemprofile\.VirtualBox\VirtualBox.xml')

**Comment by Saviq** [comment]
> I've installed VirtualBox and multipass right now in default places.

Hi @tarkhil, this is a different issue than this report, can you please [file a new one](https://github.com/canonical/multipass/issues/new?template=bug_report.md) and fill in the requested data?

**Comment by tarkhil** [comment]
Sorry.

**Comment by ruv** [comment]
> As for installing VirtualBox in a different location, its installer actually sets a system environment variable, `ORACLE_…something`. I was planning to add that to Multipass's `PATH`.

@Saviq,  in Virtual Box 6.0 on Windows 7, this variable is `VBOX_MSI_INSTALL_PATH` that looks like `VBOX_MSI_INSTALL_PATH=C:\app\VirtualBox\`

**Comment by arishem51** [comment]
> For those who don't want to reinstall VirtualBox to default location: you can create symbolic link from default location to your real VirtualBox location. In my case, I have VirtualBox installed on drive D, so creating symlink like this helped:
> 
> `mklink /d "C:\Program Files\Oracle" "D:\Program Files\Oracle"`
> 
> Do this from command prompt as Administrator

I don't know for some reason it still does not work for me, but I try reinstalling without a custom directory it works fine, thanks

**Comment by KRVPerera** [comment]
> For those who don't want to reinstall VirtualBox to default location: you can create symbolic link from default location to your real VirtualBox location. In my case, I have VirtualBox installed on drive D, so creating symlink like this helped:
> 
> `mklink /d "C:\Program Files\Oracle" "D:\Program Files\Oracle"`
> 
> Do this from command prompt as Administrator

Thanks since I did not have the Oracle folder I created it first then used below..
`mklink /d "C:\Program Files\Oracle\VirtualBox" "G:\VirtualBox"`

**Comment by parth-18-bansal** [comment]
does the virtual box need for running the multipass?

**Comment by sharder996** [comment]
@parth-18-bansal, depends on your host machine.

See https://documentation.ubuntu.com/multipass/en/latest/explanation/driver/#supported-drivers for more information
