### ISSUE TITLE
GUI on Windows?

### ISSUE THREAD

**Issue by SayusiAndo** [CanonicalLtd/multipass#973]
Hi,

I'm just scanning through the issues here and I see that in many issues GUI on Windows is mentioned. On my machine there is no GUI. I found the ```multipass-gui.exe``` in the ```$MULTIPASS_INSTALL\bin``` with Qt* and other dlls but nothing happens if I double click on the exe.

What I'm doing wrong? Is there any dependency on Qt I should install?

**Comment by townsend2010** [comment]
Hi @SayusiAndo!

At this time, it's only a system tray icon with a menu that has some basic information about the instance(s) and a couple of commands like start, suspend, and shell.  You should be able to see the Multipass icon (a large looking "M" with orange) in the Windows System Tray.  Let me know if you don't see that and we'll dig further.

**Comment by SayusiAndo** [comment]
After fresh install the icon doesn't appear in the Taskbar, it takes some time. I believe some trigger for refresh is needed from Windows side.

Thanks for the help!

**Comment by townsend2010** [comment]
@SayusiAndo,

Hmm, it shows up in the System Tray quite quickly on my machine.  I'm not sure why it takes a while for your machine.  At any rate, it does seem to work, so I'm going to close this bug.  If you want to open a bug open the slow opening, please do:)
